### ISSUE TITLE
[VL] bug of parquet read

### ISSUE THREAD

**Issue by FelixYBW** [apache/incubator-gluten#1025]
**Describe the bug**
We saw this bug from another customer again. let's track it here.
![image](https://user-images.githubusercontent.com/47296334/221340382-b31a8a40-3974-481b-bc52-17fb92a9986a.png)

**To Reproduce**
only appear in customer env.

**Comment by PHILO-HE** [comment]
This issue can be reproduced by reading a parquet file whose string column has large min/max string value. A reproducible extreme case is the column has a string containing 1000 repeated 'z' characters as the max value.

Velox community has opened a similar issue: https://github.com/facebookincubator/velox/issues/3882
And there is a PR already in the community: https://github.com/facebookincubator/velox/pull/4108
Our test shows the PR works for fixing this issue.

**Comment by FelixYBW** [comment]
> This issue can be reproduced by reading a parquet file whose string column has large min/max string value. A reproducible extreme case is the column has a string containing 1000 repeated 'z' characters as the max value.
> 
> Velox community has opened a similar issue: [facebookincubator/velox#3882](https://github.com/facebookincubator/velox/issues/3882) And there is a PR already in the community: [facebookincubator/velox#4108](https://github.com/facebookincubator/velox/pull/4108) Our test shows the PR works for fixing this issue.

Do we have a PR in Gluten?

**Comment by PHILO-HE** [comment]
> > This issue can be reproduced by reading a parquet file whose string column has large min/max string value. A reproducible extreme case is the column has a string containing 1000 repeated 'z' characters as the max value.
> > Velox community has opened a similar issue: [facebookincubator/velox#3882](https://github.com/facebookincubator/velox/issues/3882) And there is a PR already in the community: [facebookincubator/velox#4108](https://github.com/facebookincubator/velox/pull/4108) Our test shows the PR works for fixing this issue.
> 
> Do we have a PR in Gluten?

The fix is only required on velox code side. Even though the velox community patch works for solving this issue, it is still under development to avoid causing any other possible issues I guess. We will create a PR on our side once community PR is in good shape.

**Comment by FelixYBW** [comment]
@PHILO-HE can we have a temp PR to pick up Velox's PR, so customer can try?

**Comment by PHILO-HE** [comment]
> @PHILO-HE can we have a temp PR to pick up Velox's PR, so customer can try?

Yes, I just filed a PR to port upstream patches: https://github.com/oap-project/velox/pull/145. On my side, a simple test shows the PR can work well.
