### ISSUE TITLE
[VL] arrow conversion bug

### ISSUE THREAD

**Issue by FelixYBW** [apache/incubator-gluten#1026]
**Describe the bug**
Looks a bug related to arrow conversion
![image](https://user-images.githubusercontent.com/47296334/221340465-86984122-fb8e-4f5c-aba8-9dd5889c3075.png)

**To Reproduce**
customer env.

@zhztheplayer have you seen this before, any idea?

**Comment by zhztheplayer** [comment]
It's not related to Arrow. The exception wraps a TProtocalException which seems to be from thrift. More context needed to analyze this.

**Comment by FelixYBW** [comment]
From @jinchengchenghh 

We remove the C2R here when under AQE mode, because AQE will check the child plan class

[gluten/ColumnarOverrides.scala at main · oap-project/gluten (github.com)](https://github.com/oap-project/gluten/blob/main/gluten-core/src/main/scala/io/glutenproject/extension/ColumnarOverrides.scala#L412)

**Comment by FelixYBW** [comment]
@jinchengchenghh @rui-mo  how to fix this issue?

**Comment by jinchengchenghh** [comment]
Maybe firstly we should reproduce this query
