### ISSUE TITLE
Native RowToColumnar memory allocation

### ISSUE THREAD

**Issue by jinchengchenghh** [apache/incubator-gluten#1108]
Now if we use context memory pool, it will core dump, so we use static memory pool  which is not tracked instead.
Maybe because the native buffer allocated and then use ArrowArray to transfer to java side, the refcount is wrong.

Needs to fix in the future.
https://github.com/oap-project/gluten/pull/1082/files#diff-4f3b38d38be472d3634702bf87c6ac1a990997eafe4207f67ce48f7b5f550bb1R589

**Comment by jinchengchenghh** [comment]
This problem is in case of shared_ptr MemoryPool lifecycle, we need a `contextMemoryPool` when we create `NativeMemoryAllocator contextInstance()`, both of them is referred by nativeInstanceId,.
And close `contextMemoryPool` when closing `NativeMemoryAllocator` .

Do you think it is reasonable? @zhztheplayer

**Comment by zhztheplayer** [comment]
@jinchengchenghh Sounds reasonable.

But should we consider making the r2c instance reusable across batches? Then binding a pool to it, just like the usual way we applied to iterator instances.

I am not sure which one is more reasonable to current design, you can take a look.

**Comment by jinchengchenghh** [comment]
Yes, I think this is a good idea.
