### ISSUE TITLE
[VL][Spark 3.3+] support return metadataColumns from native scan insteads of fallback

### ISSUE THREAD

**Issue by gaoyangxiaozhu** [apache/incubator-gluten#2618]
Currently Velox didn't handle _metadata.* column of parquet/orc scan.

Below will fallback after this PR https://github.com/oap-project/gluten/pull/2563 or return null
```
select _metadata.file_path, _metadata.file_size
```

**Comment by gaoyangxiaozhu** [comment]
hey @zhouyuan @FelixYBW I would like to start work for metacolumn support as it is Delta support dependency.
Let me know if you think it's ok.

**Comment by zhouyuan** [comment]
Hi @gaoyangxiaozhu, sure, AFAIK no one else is looking on this issue. 

thanks, -yuan

**Comment by gaoyangxiaozhu** [comment]
> Hi @gaoyangxiaozhu, sure, AFAIK no one else is looking on this issue.
> 
> thanks, -yuan

hey @zhouyuan  i am still working for another high priority work before starting this work, i need more days to finish current work. 
I have a quick through for metacolumn support, looks it is not easy as i thought meanwhile since delta is blocked by this, would it be possible for your team to allocate partial resources to investigate this part to share insights from a design perspective could potentially fasten this part work.

I think i can start the work later next week, thank you
