### ISSUE TITLE
[CH] window with literal sort filed not supportted

### ISSUE THREAD

**Issue by shuai-xu** [apache/incubator-gluten#2957]
### Backend

CH (ClickHouse)

### Bug description

When run sql like `select row_number() over(order by 1) as id`, it throws exception as bellow:
<img width="1037" alt="image" src="https://github.com/oap-project/gluten/assets/20960838/c2365cd2-196b-4398-a2f4-a18b8b485bdf">
The subtrait plan is :
<img width="547" alt="image" src="https://github.com/oap-project/gluten/assets/20960838/b9249468-e67f-473b-a49c-029a70b95903">

### Spark version

Spark-3.3.x

**Comment by lgbo-ustc** [comment]
fixed by https://github.com/oap-project/gluten/pull/3197
