### ISSUE TITLE
[CH] Concat function result different when the argments has float type 

### ISSUE THREAD

**Issue by KevinyhZou** [apache/incubator-gluten#3289]
### Backend

CH (ClickHouse)

### Bug description

While concat string with a float type data, the result in spark is different from gluten.

Example, in the table, we have data as below
![image](https://github.com/oap-project/gluten/assets/37431499/c72a8cd9-07b7-4de1-a70f-61b53afde85b)

when we do the query `select concat('abc', ':', data) from test_tbl19 where id = 1`, the gluten query result as below
![image](https://github.com/oap-project/gluten/assets/37431499/44c5fb61-b779-424e-9760-48ec101691ca)

But the spark result is 
![image](https://github.com/oap-project/gluten/assets/37431499/8d230179-94f7-4187-92be-4f169a41d31b)

The two result is different by the point zero.

### Spark version

Spark-3.3.x

**Comment by KevinyhZou** [comment]
CAST 函数问题， gluten cast(2.0 as string) 结果为2， spark cast(2.0 as string) 结果为2.0

**Comment by zhanglistar** [comment]
Not a problem.
