### ISSUE TITLE
Allow user to fallback expression manually

### ISSUE THREAD

**Issue by zhouyuan** [apache/incubator-gluten#3369]
### Description

Gluten currently allows users to disable certain operators by setting the operator to false. e.g.
`spark.gluten.sql.columnar.hashagg = false`
This will disable columnar hash aggregate and use vanilla code path.

It maybe also useful to provide this feature at expression level, by setting some expression to false e.g.
`spark.gluten.sql.expression.get_json_object = false`
By setting this config, user can expect `get_json_object` will be executed with vanilla Spark.

**Comment by FelixYBW** [comment]
should we support all expressions? looks too many

**Comment by PHILO-HE** [comment]
Now, we have a config to allow fall back any number of specified expressions. Closing this issue as completed.
https://github.com/apache/incubator-gluten/blob/f1f6c2cf75d8a6c95f70e7c675bf7bdb94480d1c/docs/Configuration.md?plain=1#L68
