### ISSUE TITLE
[VL] memory leak reported when memory is allocated and hold not in main thread

### ISSUE THREAD

**Issue by FelixYBW** [apache/incubator-gluten#4171]
### Description

It's a known issue that when a task threads exit, it reports memory leak like below:
```
E20231211 09:28:41.554893 79095 Exceptions.h:69] Line: /home/binweiyang/gluten/ep/build-velox/build/velox_ep/velox/common/memory/MemoryPool.cpp:398, Function:~MemoryPoolImpl, Expression: (usedReservationBytes_ == 0) && (reservationBytes_ == 0) && (minReservationBytes_ == 0) Bad memory usage track state: Memory Pool[op.0.0.0.TableScan LEAF root[WholeStageIterator_root] parent[node.0] MALLOC track-usage thread-safe]<unlimited max capacity unlimited capacity used 8.42MB available 592.00KB reservation [used 8.42MB, reserved 9.00MB, min 0B] counters [allocs 27507, frees 27497, reserves 0, releases 1, collisions 0])>, Source: RUNTIME, ErrorCode: INVALID_STATE
terminate called after throwing an instance of facebook::velox::VeloxRuntimeError
  what():  Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: Bad memory usage track state: Memory Pool[op.0.0.0.TableScan LEAF root[WholeStageIterator_root] parent[node.0] MALLOC track-usage thread-safe]<unlimited max capacity unlimited capacity used 8.42MB available 592.00KB reservation [used 8.42MB, reserved 9.00MB, min 0B] counters [allocs 27507, frees 27497, reserves 0, releases 1, collisions 0])>
Retriable: False
Expression: (usedReservationBytes_ == 0) && (reservationBytes_ == 0) && (minReservationBytes_ == 0)
Function: ~MemoryPoolImpl
File: /home/binweiyang/gluten/ep/build-velox/build/velox_ep/velox/common/memory/MemoryPool.cpp
Line: 398
Stack trace: 
```

It happens when multiple threads are used and hold the memory except the main task thread. Like the IO threads used by DirectBufferInput, io threads used by split preload.

Currently we use a temp solution that we wait up to 30s by default until the IO threads release the memory. The fundemental solution is that we should manually make sure the memory holded by IO threads must be released before the main thread exits. 

The directbufferinput is enabled by default now, but preload split is disabled.

@zhztheplayer @zhli1142015 @Yohahaha

**Comment by FelixYBW** [comment]
To direct buffer, the memory allocated by IO threads are here: https://github.com/facebookincubator/velox/blob/9d7d4e8a51e54ffc7af42f71f0d0f8bc21ad9824/velox/dwio/common/DirectBufferedInput.cpp#L265

**Comment by zhli1142015** [comment]
> The fundemental solution is that we should manually make sure the memory holded by IO threads must be released before the main thread exits.

I agree this, I'm making changes to support this for splits preloading.

**Comment by FelixYBW** [comment]
The root cause of directinputbuffer is that the io thread is doing a rowgroup prefetch. It either because the rowgroup prefetch exceeds the split boundary or the rowgroup is fetched again. If it's former we should add the check before rowgroup prefetch, if the latter we need to cancel the read before we fetch it again. Another solution is to cancel andy pending fetches before the task ends.

**Comment by zhli1142015** [comment]
I checked the [Asyncsource](https://github.com/facebookincubator/velox/blob/main/velox/common/base/AsyncSource.h) also. If `move()` is executed before `prepare()`, then the `make()` would be executed in task thread instead of IO threads. Then the task doesn't wait the result from IO thread and finish first, but the func which holds [`taskHolder`](https://github.com/facebookincubator/velox/blob/main/velox/common/base/AsyncSource.h) is waiting the IO thread slots from thread pool. This caused task finished task instance is not destructured.
Here we wait 30s, if IO thread pool is busy, and no slots available for 30s, then the errors happened.
For split preloading I think we may leverage weak_ptr to hold the [`split `](https://github.com/facebookincubator/velox/blob/main/velox/common/base/AsyncSource.h) object, if it can be locked then we containue the work in IO threads.

**Comment by zhli1142015** [comment]
> I checked the [Asyncsource](https://github.com/facebookincubator/velox/blob/main/velox/common/base/AsyncSource.h) also. What I observed is that if `move()` is executed before `prepare()`, then the `make_` is executed in task thread (`move()`) instead of IO pool threads. The task finishes first and it doesn't wait the func (which holds [`taskHolder`](https://github.com/facebookincubator/velox/blob/main/velox/common/base/AsyncSource.h)) executed in IO thread. This caused task finished, but task instance is not destructured.
> 
> Here we wait 30s. If the IO thread pool is busy and no slots are available during this time, errors occur.
> 
> For split preloading I think we may need to add `close` function in `Asyncsource`, either waiting the ongoing reading finishes or reset `make_` if it doesn't start.

here is a pr to solve this issue for split preloading, https://github.com/facebookincubator/velox/pull/8181. needs to figure out how to unit test this.

**Comment by FelixYBW** [comment]
FYI, the UML of table scan
![image](https://www.plantuml.com/plantuml/png/RP8nJyCm48Nt-nKt0bBw0r27KZg0n808UtIrhyB2YLEVtGNuxxX6gHkJgUfxttls-RAHG3x4tW8eIoBuJdlBhQ81lW0n3kOOkHk3Hqs1MXUzuWv-9lh9d7XtCUg8ZDQ4DoRDlaiEQTsUbPlRKj0Mf4xlIRY4HyyZUVvNC6MByah-6BcKoWTvrhdIPsrBacSe5PCwfyqmnd0DRkFXmCbzFXk9BMVkZ6SLQX_nb5JdKJcoB8hrYoCjNPrxlBPpxi5QfoWODs3FVRTF_pwJt0OAKL3oJxxOx4XSVpVDubtWRyOCL0y4butZNTDK6qM0gmrbO8fLOB9couI5Q-1wjQeEk9y-YiL0Rbrw8oWxGvUOQjhPX1aeF030XWSTU_iB)

**Comment by FelixYBW** [comment]
@zhanglistar do we have any way to make sure the object destruction sequence? Like the memory pool is a reference in the DirectBufferedInput, so we must make sure it's destructed before the memory pool. How do we guarantee this?

Looks there is no clean up mechanism of the pipleline objects or global objects, we should clean up the context before object destruction.

**Comment by FelixYBW** [comment]
The memory pool issue is caused by DirectBufferedInput's speculative prefetch of a column. e.g. we have SQL:

`Select A, B, C where C=1`

It may prefetch the columnChunk of  A and B where C actually != 1. In this way, the task is already finished but the fetching is still on the road which caused the issue.

It does set the loads's status to Canceled in destructor, but doesn't cancel or waiting the fetched data. This also assume that DirectBufferedInput must be destructed before memory pool

**Comment by FelixYBW** [comment]
> here is a pr to solve this issue for split preloading, [facebookincubator/velox#8181](https://github.com/facebookincubator/velox/pull/8181). needs to figure out how to unit test this.

We need a PR in Gluten to call the close(), right? Let's clean up everything there

**Comment by zhli1142015** [comment]
> > here is a pr to solve this issue for split preloading, [facebookincubator/velox#8181](https://github.com/facebookincubator/velox/pull/8181). needs to figure out how to unit test this.
> 
> We need a PR in Gluten to call the close(), right? Let's clean up everything there

Regarding my pull request, I think the driver will close all operators during termination, eliminating the need for an explicit call in Gluten.
https://github.com/facebookincubator/velox/blob/main/velox/exec/Driver.cpp#L818C14-L818C28

**Comment by FelixYBW** [comment]
Thank you, so it's called when task is finished here:
https://github.com/facebookincubator/velox/blob/523e561d3da99a78a33c4e22106ba7d1cf83c8a2/velox/exec/Driver.cpp#L722

**Comment by FelixYBW** [comment]
Close this PR. Reasons are clear and PRs are submited. No need to change Gluten code

**Comment by FelixYBW** [comment]
@zhli1142015 bad news, even with split preload disabled and the direct buffer input fixed, some query still reports memleak, sizes are mostly 32K. Not sure where the leak is though.

**Comment by FelixYBW** [comment]
Not shown in long tiem. Maybe already fixed in Velox. Close for now.
