### ISSUE TITLE
[VL] support partial window in Spark 3.5

### ISSUE THREAD

**Issue by zhouyuan** [apache/incubator-gluten#4836]
### Description

It's very similar with Window
https://issues.apache.org/jira/browse/SPARK-37099

**Comment by ayushi-agarwal** [comment]
@zhouyuan Is someone working on this, if not I can work on this.

**Comment by zhouyuan** [comment]
I know @Jkself may have some plans. @JKself please suggest

Thanks -yuan

________________________________

**Comment by JkSelf** [comment]
@ayushi-agarwal I have done some research before, and can map the `RankLimit `operator in Spark to the `TopNRowNumber `operator in Velox. However, I am currently busy with other things and have not started the relevant implementation. If you have time, you are welcome to help support this feature.

**Comment by ayushi-agarwal** [comment]
@JkSelf There are three functions, row_number, rank and dense_rank which are supported by WindowGroupLimit operator in spark. We can map row_number to TopNRowNumber but to support other two it would need more changes.
There can be two approaches:
1. To convert this WindowGroupLimit to Window plus Filter node. This won't require any change in velox.
2. Modify TopNRowNumber or create two more operators to support rank and dense_rank. This would require change in velox.
Want to know your input on this that which approach would be better?

**Comment by JkSelf** [comment]
@ayushi-agarwal Apologies for the delayed response. If method 1 is feasible, I would prefer method 1. Regarding method 1, I have a question I would like to ask: It seems that the Window operator in Velox does not have an option for partial mode. If that is the case, are we unable to map to Window + Filter without modifying the code? Correct me if wrong understand. Thanks.

**Comment by ayushi-agarwal** [comment]
@JkSelf The plan after optimization in spark looks like Plan -> Sort -> WindowGroupLimit partial -> Exchange -> Sort -> WindowGroupLimit final -> WindowExec -> Filter.
In Gluten this can be converted to Plan -> Sort -> Window -> Filter -> Exchange -> Sort -> Window -> Filter. Mode will not be required in this case. Please let me know if my understanding is not correct or if there is any issue with this approach.

**Comment by JkSelf** [comment]
@ayushi-agarwal For the Window + Filter in the Gluten plan, can it be understood that after the Window operation is completed, the Filter selects the top n records from the limit? If that's the case, do we still need to calculate all the results within the Window and then filter out the final results in the Filter? If so, the outcome would be correct, but it likely wouldn't result in a performance improvement.

**Comment by ayushi-agarwal** [comment]
@JkSelf Apologies for not mentioning it my previous comment. This is drawback of going through this approach, here only performance gain that we will see will come from less rows being processed after filter operator starting from exchange, but first window will have to process all the rows which would make it less performant. To prevent this, we will have to go with second approach and make changes in Velox.

**Comment by JkSelf** [comment]
@ayushi-agarwal Yes, Method 1 cannot solve the PartialWindow issue; not only is there no performance improvement, but it also fails to address the out-of-memory (oom) problem for Q67 under tight memory conditions. We need to adopt Method 2 to map the RankLimit operator in Spark to the TopNRowNumber operator in Velox.
Currently, there is an issue that the documentation for TopNRowNumber states it only supports the row_number function. However, from looking at the code, it seems that it should also be able to support rank and dense_rank. I have added a test in Velox's unit tests to verify that rank and dense_rank can work using TopNRowNumber.
I will confirm this with the Velox community later. Could you first support the mapping of RankLimit to Velox's TopNRowNumber in Gluten? Thanks.

**Comment by ayushi-agarwal** [comment]
@JkSelf Sure, I will try to raise a PR for the first task by end of Thursday.

**Comment by mskapilks** [comment]
@JkSelf  Is any progress made with step 2 and 3 and if you could point to any ongoing discussions?
Thanks

**Comment by JkSelf** [comment]
@mskapilks We have proposed one discussion in velox community https://github.com/facebookincubator/velox/discussions/9404. And @aditi-pandit is working on the detailed implementations.

**Comment by aditi-pandit** [comment]
@mskapilks : I have started work for this in Presto/Velox. Will send out a PR by early next week.
