### ISSUE TITLE
Bump Celeborn version 

### ISSUE THREAD

**Issue by SteNicholas** [apache/incubator-gluten#4903]
### Description

Celeborn has already released [v0.3.1-incubating](https://github.com/apache/incubator-celeborn/releases/tag/v0.3.1-incubating), [v0.3.2-incubating](https://github.com/apache/incubator-celeborn/releases/tag/v0.3.2-incubating) and [v0.4.0-incubating](https://github.com/apache/incubator-celeborn/releases/tag/v0.4.0-incubating). The released versions support Gluten. The version of Celeborn in Gluten is 0.3.1-incubating, which could be bumped the released versions.

**Comment by SteNicholas** [comment]
@kerwin-zk, did you work on upgrading the version of Celeborn? If not, I will take this upgrade of Celeborn. cc @ulysses-you.

**Comment by ulysses-you** [comment]
Better to let Gluten compatible with both celeborn 0.3.x and 0.4.x.

cc @pan3793 @zzcclp

**Comment by pan3793** [comment]
Given there is no patched version on Celeborn 0.4 serials yet and 0.3 is the most stable version for production cases, I'm +1 for making Gluten compatible with both Celeborn 0.3 and 0.4

**Comment by zzcclp** [comment]
use maven profile to specify the compile version of the celeborn for 0.3.x or 0.4.x, lgtm.

**Comment by kerwin-zk** [comment]
> @kerwin-zk, did you work on upgrading the version of Celeborn? If not, I will take this upgrade of Celeborn. cc @ulysses-you.

@SteNicholas  This is already under design.

**Comment by kerwin-zk** [comment]
I will submit a pr later.
