### ISSUE TITLE
Bump Iceberg version

### ISSUE THREAD

**Issue by SteNicholas** [apache/incubator-gluten#4933]
### Description

Iceberg has already released [1.4.0](https://github.com/apache/iceberg/releases/tag/apache-iceberg-1.4.0), [1.4.1](https://github.com/apache/iceberg/releases/tag/apache-iceberg-1.4.1), [1.4.2](https://github.com/apache/iceberg/releases/tag/apache-iceberg-1.4.2), [1.4.3](https://github.com/apache/iceberg/releases/tag/apache-iceberg-1.4.3) and [1.5.0](https://github.com/apache/iceberg/releases/tag/apache-iceberg-1.5.0). Meanwhile, Gluten only supports the Iceberg 1.3.1 version, which could support bumping the released version.

**Comment by SteNicholas** [comment]
cc @liujiayi771.

**Comment by j7nhai** [comment]
> The current implementation has compatibility issues with the latest version of Iceberg that need to be resolved.

Hi, @liujiayi771 Can you explain some detail of compatibility issues? We are currently using both iceberg 1.3 & 1.4, and we look forward to resolve these issues.

**Comment by liujiayi771** [comment]
@j7nhai We have already upgraded the Iceberg version of Spark 3.4 to 1.4.3. The compatibility issues mentioned above might have been partially resolved. I don't remember the specific details, but you can try upgrading the version. If the end-to-end tests and unit tests can pass, it should be fine.
