### ISSUE TITLE
disable some physic plan transform

### ISSUE THREAD

**Issue by RaoZhiRou-Z** [apache/incubator-gluten#4970]
### Description

[CH]  is there any configuration that can disable the conversion of some physical plans, such as the reading and writing of  file system, because the file system we used is not compatible

**Comment by liujiayi771** [comment]
Maybe you can use these configurations:
* spark.gluten.sql.columnar.filescan = false
* spark.gluten.sql.native.writer.enabled = false

**Comment by RaoZhiRou-Z** [comment]
> Maybe you can use these configurations:
> 
> * spark.gluten.sql.columnar.filescan = false
> * spark.gluten.sql.native.writer.enabled = false

thanks! i will try this.

**Comment by RaoZhiRou-Z** [comment]
i use clickhouse backend and add (spark.gluten.sql.columnar.filescan = false、spark.gluten.sql.native.writer.enabled = false), but But there are still errors：

**Comment by liujiayi771** [comment]
@RaoZhiRou-Z I am not very familiar with the CH backend. You need to change the issue title to start with [CH] so that the people related to CH can assist you.

**Comment by RaoZhiRou-Z** [comment]
> @RaoZhiRou-Z I am not very familiar with the CH backend. You need to change the issue title to start with [CH] so that the people related to CH can assist you.

ok, the config you mentioned is useful for velox？

**Comment by liujiayi771** [comment]
@RaoZhiRou-Z Yes. But you can check the actual plan node name of the scan in vanilla Spark, is it `FileScan` or `BatchScan` or `HiveTableScan`. There are three kinds of configuration for scan fallback. You can find them in `GlutenConfig` class.
