### ISSUE TITLE
UDF with one more return type can't be registered to gluten

### ISSUE THREAD

**Issue by liujp** [apache/incubator-gluten#4988]
### Backend

VL (Velox)

### Bug description

In UDF register to gluten, using unordered_map{udf_name, udf_return_type} to register the udf to gluten, as follows:
<img width="937" alt="image" src="https://github.com/apache/incubator-gluten/assets/11934146/3852f557-d0b5-4ed0-9c64-bf1c39e1086c">
so, in this method, udf registered to gluten can only using one return type. but if I have a UDF that int myudf(int, int) and string myudf(string, int).if so, I can't register one udf with one more return type

**Comment by zhouyuan** [comment]
CC @marin-ma

**Comment by liujp** [comment]
done

**Comment by liujp** [comment]
done
