### ISSUE TITLE
[CH] Function regexp_extract diff from spark and gluten

### ISSUE THREAD

**Issue by KevinyhZou** [apache/incubator-gluten#5096]
### Backend

CH (ClickHouse)

### Bug description

while use function `regexp_extract` to get result from string with \n at end, the gluten can not extract, return `NULL`, But spark return corretly result.

### Spark version

Spark-3.3.x

**Comment by PHILO-HE** [comment]
Hi @KevinyhZou, does clickhouse also use RE2?

**Comment by zhanglistar** [comment]
> Hi @KevinyhZou, does clickhouse also use RE2?

Yes.
