### ISSUE TITLE
[VL]Support cast date as timestamp in velox

### ISSUE THREAD

**Issue by dcoliversun** [apache/incubator-gluten#5102]
### Description

At the moment, gluten validator rejects the cast of date to varchar/timestamp.
https://github.com/apache/incubator-gluten/blob/e9034ff5e2ec4cce8cd5defaf2ade9b44b8c8aa3/cpp/velox/substrait/SubstraitToVeloxPlanValidator.cc#L277-L287

And velox already supports.   
 https://github.com/facebookincubator/velox/blob/8f0adb1fa6a2553b58f0360224418eb7c5306608/velox/expression/CastExpr.cpp#L147-L204

After validation, we need to remove the check in the `SubstraitToVeloxPlanValidator.cc`

**Comment by dcoliversun** [comment]
result is here
```shell
scala> spark.read.parquet("/opt/data").createOrReplaceTempView("view")

scala> spark.sql("select * from view").show
+----------+
|dateColumn|
+----------+
|2023-01-01|
|2023-01-03|
|2023-01-02|
+----------+

scala> val newDf = spark.sql("select cast(dateColumn as string) from view")
newDf: org.apache.spark.sql.DataFrame = [dateColumn: string]

scala> newDf.explain
== Physical Plan ==
VeloxColumnarToRowExec
+- ^(3) ProjectExecTransformer [cast(dateColumn#0 as string) AS dateColumn#15]
   +- ^(3) NativeFileScan parquet [dateColumn#0] Batched: true, DataFilters: [], Format: Parquet, Location: InMemoryFileIndex(1 paths)[file:/opt/data], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<dateColumn:date>
```

**Comment by dcoliversun** [comment]
cc @rui-mo

**Comment by rui-mo** [comment]
Hi @dcoliversun, I believe the validation logic is if `toType` is **not** varchar, the execution will fallback.

>    if (toType->kind() != TypeKind::VARCHAR) { 
     LOG_VALIDATION_MSG("Casting from DATE to " + toType->toString() + " is not supported."); 
     return false; 
   } 

About timestamp to varchar, probably we can check the detailed fallback reason for what is lacked.

**Comment by dcoliversun** [comment]
@rui-mo Hi, thanks for your help. It's my bad. I mistakenly thought that varchar and timestamp had the same logic. Let me draft this PR. Then I will check the reason of fallback.

**Comment by dcoliversun** [comment]
@rui-mo cast date as timestamp is ok. I will update this pr soon.
```shell
scala> val df1 = spark.sql("select cast(dateColumn as timestamp) from view")
df1: org.apache.spark.sql.DataFrame = [dateColumn: timestamp]

scala> df1.explain
== Physical Plan ==
VeloxColumnarToRowExec
+- ^(3) ProjectExecTransformer [cast(dateColumn#0 as timestamp) AS dateColumn#10]
   +- ^(3) NativeFileScan parquet [dateColumn#0] Batched: true, DataFilters: [], Format: Parquet, Location: InMemoryFileIndex(1 paths)[file:/opt/data], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<dateColumn:date>



scala> df1.show
+-------------------+
|         dateColumn|
+-------------------+
|2023-01-01 00:00:00|
|2023-01-03 00:00:00|
|2023-01-02 00:00:00|
+-------------------+


scala> df1.schema
res5: org.apache.spark.sql.types.StructType = StructType(StructField(dateColumn,TimestampType,true))
```

**Comment by rui-mo** [comment]
@dcoliversun Thank you.
