### ISSUE TITLE
[VL] Gluten CPP Build fails with not-found crypto_LIBRARY on centos 8

### ISSUE THREAD

**Issue by dcoliversun** [apache/incubator-gluten#5178]
### Problem description

Detail is [here](https://github.com/dcoliversun/gluten/actions/runs/8463669591/job/23186962524)
When I ran the `dev/package.sh`script on centos8, I got the following error. 
```plain
-- Try finding aws-cpp-sdk-core
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find crypto (missing: crypto_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/lib64/s2n/cmake/modules/Findcrypto.cmake:75 (find_package_handle_standard_args)
  /usr/share/cmake/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /usr/local/lib64/s2n/cmake/s2n-config.cmake:9 (find_dependency)
  /usr/share/cmake/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /usr/local/lib64/aws-c-io/cmake/aws-c-io-config.cmake:4 (find_dependency)
  /usr/share/cmake/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /usr/local/lib64/aws-c-http/cmake/aws-c-http-config.cmake:3 (find_dependency)
  /usr/share/cmake/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /usr/local/lib64/aws-crt-cpp/cmake/aws-crt-cpp-config.cmake:3 (find_dependency)
  /usr/share/cmake/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /usr/local/lib64/cmake/aws-cpp-sdk-core/aws-cpp-sdk-core-config.cmake:13 (find_dependency)
  /usr/local/lib64/cmake/AWSSDK/AWSSDKConfig.cmake:310 (find_package)
  velox/CMakeLists.txt:277 (find_package)
```

### System information

Velox System Info v0.0.2
Commit: 1cda804b994ba650b4a9b16a2d812eefde969983
CMake Version: 3.20.2
System: Linux-4.18.0-80.11.2.el8_0.x86_64
Arch: x86_64
C++ Compiler: /opt/rh/gcc-toolset-9/root/usr/bin/c++
C++ Compiler Version: 9.2.1
C Compiler: /opt/rh/gcc-toolset-9/root/usr/bin/cc
C Compiler Version: 9.2.1
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

**Comment by dcoliversun** [comment]
@PHILO-HE could you please check it? I think I already installed openssl on centos successfully

**Comment by PHILO-HE** [comment]
@dcoliversun, let me try to reproduce it.

**Comment by dcoliversun** [comment]
@PHILO-HE hi, did you successfully reproduce this case?

**Comment by PHILO-HE** [comment]
> @PHILO-HE could you please check it? I think I already installed openssl on centos successfully

Hi @dcoliversun, I tried many times, but have not reproduced this issue. I tried with a clean centos-8 docker.

**Comment by dcoliversun** [comment]
> > @PHILO-HE could you please check it? I think I already installed openssl on centos successfully
> 
> Hi @dcoliversun, I tried many times, but have not reproduced this issue. I tried with a clean centos-8 docker.

thanks, I have tried to fix all time, please see https://github.com/dcoliversun/gluten/actions. And I couldn't find the solution yet. I run on a clean server with centos-8, got the same error.

**Comment by PHILO-HE** [comment]
Hi @dcoliversun, I just reproduced this issue. Seems it is caused by the lacking of `libcrypto.a`. After I install it, e.g, under `/usr/local/lib64/libcrypto.a`, the `dev/package.sh` can pass.

**Comment by dcoliversun** [comment]
@PHILO-HE hi, I run `package.sh` with your commit. And it fails when building `oap-project/libhdfs3`
```plain
CMake Error at src/CMakeLists.txt:52 (message):
  Please install the Yasm assembler to build libhdfs3


-- Configuring incomplete, errors occurred!
See also "/__w/gluten/gluten/ep/build-velox/build/velox_ep/_build/CMakeFiles/CMakeOutput.log".
See also "/__w/gluten/gluten/ep/build-velox/build/velox_ep/_build/CMakeFiles/CMakeError.log".
+ ninja -C _build install
ninja: error: loading 'build.ninja': No such file or directory
ninja: Entering directory `_build'

real	0m1.542s
user	0m1.090s
sys	0m0.294s
+ echo 'Failed to run install_libhdfs3 .'
+ exit 1
Failed to run install_libhdfs3 .
```

**Comment by PHILO-HE** [comment]
@dcoliversun, this is another issue, due to upstream/velox's change. I just created a pr https://github.com/apache/incubator-gluten/pull/5261. Please help verify it. Thanks!

**Comment by dcoliversun** [comment]
@PHILO-HE Verifing it with https://github.com/dcoliversun/gluten/actions/runs/8519762997
