### ISSUE TITLE
Correct boost lib path

### ISSUE THREAD

**Issue by wForget** [apache/incubator-gluten#5189]
### Backend

VL (Velox)

### Bug description

Currently `package.sh` copies `libboost_*` from `/usr/lib/${ARCH}-linux-gnu/`, after upgrading to 1.84.0,  no such file error will occur.

![image](https://github.com/apache/incubator-gluten/assets/17894939/984056d4-488b-420c-aba6-eadb18851a7b)

Actually it is installed in `/usr/local/lib/`:

![image](https://github.com/apache/incubator-gluten/assets/17894939/f458bd15-5214-44ed-95d4-2a3046b6af1c)

`install_boost` function in velox specifies `/usr/local` prefix

https://github.com/facebookincubator/velox/blob/2d899d4fedf8977cfc551e5c1cec3ca79273f36a/scripts/setup-ubuntu.sh#L79

more detail log: https://github.com/wForget/kyuubi/actions/runs/8469948686/job/23206490956

### Spark version

None

**Comment by wForget** [comment]
I guess the previous `/usr/lib/${ARCH}-linux-gnu/libboost_*.so.1.74.0` was introduced by `sudo apt-get install libboost-all-dev`.

https://github.com/apache/incubator-gluten/blob/dee18e7afdffa1301954ded7b71b527232b7be43/dev/setup-qat-ubuntu.sh#L14

**Comment by marin-ma** [comment]
Velox build script installs libboost-all-dev before this patch https://github.com/facebookincubator/velox/pull/8679/files#diff-960a11a4bac38369ab5702ab18b60cac5dff8a4e14a732b4adfc75964bc23b22

You may need to run `sudo apt purge libboost-all-dev` on your platform

**Comment by wForget** [comment]
> You may need to run `sudo apt purge libboost-all-dev` on your platform

Thanks, I will try it. BTW, `libboost-all-dev` was not installed in advance in my failed action.

https://github.com/wForget/kyuubi/actions/runs/8469948686/workflow

![image](https://github.com/apache/incubator-gluten/assets/17894939/899afffc-ab91-44ac-ae34-e4516ea1334c)
