### ISSUE TITLE
UDF and UDAF do not support  Variable length parameter

### ISSUE THREAD

**Issue by liujp** [apache/incubator-gluten#5197]
if I want to run a sql:
select fun(c1, c2, c3, c4) from table;
select fun("add_4_cols",  c1, c2, c3, c4) from table;
select fun("add_6_cols",  c1, c2, c3, c4, c5, c6) from table;
so, I want to use variable length parameter in udf/udaf function, and how to realize it;

<img width="733" alt="image" src="https://github.com/apache/incubator-gluten/assets/11934146/d1e7a247-5bbf-4683-ad32-754397dfe12a">

**Comment by liujp** [comment]
@marin-ma thx~

**Comment by marin-ma** [comment]
@liujp The UDF support in Gluten is still under active development and is immature as for now. But seems like your use cases are very widely covered. Apart from the unsupported functionalities that are already known, to further enhance the UDF framework, it would be very helpful if you could share specific examples from your use cases and problems you've met.

It's also welcomed if you are interested in implementing this feature.

**Comment by liujp** [comment]
> @liujp The UDF support in Gluten is still under active development and is immature as for now. But seems like your use cases are very widely covered. Apart from the unsupported functionalities that are already known, to further enhance the UDF framework, it would be very helpful if you could share specific examples from your use cases and problems you've met.
> 
> It's also welcomed if you are interested in implementing this feature.

I am a newer for gluten project and recently received some requirements related to the use of UDFs. I will do my best to contribute some of my use cases, and I am also very pleased to  implement this feature
