### ISSUE TITLE
UD(A)F doesn't support array type

### ISSUE THREAD

**Issue by liujp** [apache/incubator-gluten#5236]
### Backend

VL (Velox)

### Bug description

<img width="1163" alt="image" src="https://github.com/apache/incubator-gluten/assets/11934146/a0654988-66d9-4e08-a193-7de5da0e7c16">

UD(A)F argument registers an array type, the type can be registered successfully, but then execute a sql query, an  error throws as:
<img width="1572" alt="image" src="https://github.com/apache/incubator-gluten/assets/11934146/fbdb7143-67f2-4b48-94f5-06c762d5af80">

for the reason that:
<img width="1510" alt="image" src="https://github.com/apache/incubator-gluten/assets/11934146/11e34e24-8be6-412b-a4e4-5240374bbad9">

**Comment by liujp** [comment]
@marin-ma

**Comment by liujp** [comment]
<img width="1580" alt="image" src="https://github.com/apache/incubator-gluten/assets/11934146/05025623-ff1f-4247-9c44-79af8b4d2d46">

**Comment by marin-ma** [comment]
Which Gluten commit do you use? It should be already fixed in #4686

**Comment by liujp** [comment]
> Which Gluten commit do you use? It should be already fixed in #4686

sorry, my branch is to old(021b6eb5e61be256472315f12fec43bd9bcc9652. 2023-12).
