### ISSUE TITLE
[VL] Add SampleExec operator support

### ISSUE THREAD

**Issue by gaoyangxiaozhu** [apache/incubator-gluten#5315]
### Description

Using this issue to track support for sampleExec operation. https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/execution/basicPhysicalOperators.scala#L313

**Comment by gaoyangxiaozhu** [comment]
Hey @zhouyuan / @FelixYBW / @rui-mo ,

I'm starting to work on this feature, and here's a quick draft to share my ideas and one basic but crucial question need you help confirm before i start the detailed design doc and code implement.

In Velox, there's no such sampleNode available, but it does support random sampling push down with jimmy's this PR [Table sampling push down](https://github.com/facebookincubator/velox/commit/3d9cf528b065052e3d7ff6d0603035f5b56ebfc3#diff-58b64d1e01b72d7e092a092708f13e1a2785f0151709bce18b1c736a0c8d28ee) , it support accelerate random sampling based on Bernoulli trials by push the random sampling operations to table scan.

So, my current idea is to leverage the existing sample filter pushdown logic. This involves transforming the vanilla Spark sampleExec node into a filter node, with the sample operation transformed into a sample filter expression., ultimately pushing the random sampling filter  down to the scan filter.

The issue here is that Spark uses  [XORShiftRandom](https://github.com/apache/spark/blob/207d675110e6fa699a434e81296f6f050eb0304b/core/src/main/scala/org/apache/spark/util/random/RandomSampler.scala#L57C1-L58C49) pseudorandom number generator and [Bernoulli trials based sampler](https://github.com/apache/spark/blob/207d675110e6fa699a434e81296f6f050eb0304b/core/src/main/scala/org/apache/spark/util/random/RandomSampler.scala#L116C1-L123C6) for sampling, while Velox employs__gnu_cxx::sfmt19937 random number generator with geometric distribution for sampling, checking here [RandomUtil](https://github.com/facebookincubator/velox/blob/main/velox/common/base/RandomUtil.h#L93C1-L95C33). Thus, even with the same `fraction` and `seed` (which user can specify), the sampled results will differ from the vinalla Spark results vs velox.

So, my basic but crucial question here is whether it's acceptable for such correctness issues to exist in the sample scenario when offload to velox. 

If it is acceptable, I'll then start by drafting a design document in the gluten channel and then proceed with the code implementation.

**Comment by gaoyangxiaozhu** [comment]
kindly ping @zhouyuan / @rui-mo / @FelixYBW

**Comment by rui-mo** [comment]
Hi @gaoyangxiaozhu, thanks for working on this issue. I remember the 'rand' function in Velox also uses different algorithms with Spark, so perhaps they are similar cases. I assume the result difference should be acceptable. @PHILO-HE How do you think?

**Comment by PHILO-HE** [comment]
> Hi @gaoyangxiaozhu, thanks for working on this issue. I remember the 'rand' function in Velox also uses different algorithms with Spark, so perhaps they are similar cases. I assume the result difference should be acceptable. @PHILO-HE How do you think?

@gaoyangxiaozhu, I agree with Rui. It's no correctness issue. We just need to make sure same result is produced if same seed is used for two runs.

**Comment by gaoyangxiaozhu** [comment]
super thanks @rui-mo / @PHILO-HE for the confirm.
