### ISSUE TITLE
[VL] Build failed in macOs M1

### ISSUE THREAD

**Issue by zml1206** [apache/incubator-gluten#5343]
### Problem description

`./dev/buildbundle-veloxbe.sh --build_type=RelWithDebInfo --enable_vcpkg=OFF`
Failed when make folly-deps. 

### System information

Velox System Info v0.0.2
Commit: 73a243c45e89a5f1ddfc4e7e39c699cd24ffd77a
CMake Version: 3.29.1
System: Darwin-22.6.0
Arch: x86_64
C++ Compiler: /Library/Developer/CommandLineTools/usr/bin/c++
C++ Compiler Version: 14.0.3.14030022
C Compiler: /Library/Developer/CommandLineTools/usr/bin/cc
C Compiler Version: 14.0.3.14030022
CMake Prefix Path: /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr;/usr/local;/usr;/;/usr/local/Cellar/cmake/3.29.1;/usr/local;/usr/X11R6;/usr/pkg;/opt;/sw;/opt/local

### CMake log

```bash
CMake Error at CMake/folly-deps.cmake:306 (target_link_libraries):
  The link interface of target "folly_deps" contains:

    fmt::fmt

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  CMakeLists.txt:127 (include)
```

**Comment by zml1206** [comment]
cc @ulysses-you @xumingming Could you help to check it? I tried it on multiple macOs and got the same error, MacOSX12 and MacOSX13. Thanks.

**Comment by zml1206** [comment]
Thanks, there is indeed a problem compiling velox. @xumingming

**Comment by zml1206** [comment]
Local environmental issues.

**Comment by wenjiecn** [comment]
I encountered the same problem because sudo could not find cmake when using the installation script. Install cmake in the "/usr/local/bin" directory to solve the problem.
