### ISSUE TITLE
GCC 11 warns that writing 1 byte into a region of size 0 [-Wstringop-overflow=]

### ISSUE THREAD

**Issue by yma11** [apache/incubator-gluten#5511]
### Backend

VL (Velox)

### Bug description

Following error happens during compilation:

```
..../Parquet_Read_Fuzz/ep/build-velox/build/velox_ep/./velox/vector/SelectivityVector.h:160:20: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
  160 |       allSelected_ = false;
      |       ~~~~~~~~~~~~~^~~~~~~
```

### Spark version

None

### System information

Velox System Info v0.0.2
Commit: a3e30af3a594d9ba3bc086f700fa62cd43a27111
CMake Version: 3.22.1
System: Linux-5.15.0-102-generic
Arch: x86_64
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 11.4.0
C Compiler: /usr/bin/cc
C Compiler Version: 11.4.0
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

\nThe results will be copied to your clipboard if xclip is installed.

**Comment by FelixYBW** [comment]
A quick fix:
```
  void clearAll() {
    bits::fillBits(bits_.data(), 0, size_, false);
    begin_ = 0;
    end_ = 0;
#pragma GCC diagnostic ignored "-Wstringop-overflow"
    allSelected_ = false;
#pragma GCC diagnostic pop
  }

  /**
   * Sets the vector to all selected.
   */
  void setAll() {
    bits::fillBits(bits_.data(), 0, size_, true);
    begin_ = 0;
    end_ = size_;
#pragma GCC diagnostic ignored "-Wstringop-overflow"
    allSelected_ = true;
#pragma GCC diagnostic pop
  }
```

What GCC version does Velox use? why they can compile?

**Comment by yma11** [comment]
Hi binwei,

I have met the same issue when I deployed parquet read fuzzer test. This is caused by different compile flag used in Gluten --- "-march=native -std=c++17 -mno-avx512f -mbmi2 $ADDITIONAL_FLAGS" thus velox upstream doesn’t have this issue. Another optional fix is to add “-Wno-stringop-overflow” but it will cover the errors which should be caught.

Thanks,
Yan

**Comment by FelixYBW** [comment]
It's odd I got this error when build gluten using vcpkg on a clean machine today.

**Comment by acvictor** [comment]
I also ran into this. Would explicitly initializing allSelected_ to nullopt fix it?

**Comment by yma11** [comment]
I don't think so but you may have a try. It's kind of not related with the specific code. The logic of this line code seems good.

**Comment by dcoliversun** [comment]
Hi, any update about this issue? I get same error with clean machine.
```plain
Velox System Info v0.0.2
Commit: 7467fe427159bd757d2eb911b0b6ea1da4928c19
CMake Version: 3.28.3
System: Linux-5.15.0-101-generic
Arch: x86_64
CPU Name: Model name:                         Intel(R) Xeon(R) Platinum 8369B CPU @ 2.70GHz
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 11.4.0
C Compiler: /usr/bin/cc
C Compiler Version: 11.4.0
CMake Prefix Path: /usr/local;/usr;/;/usr/local/lib/python3.10/dist-packages/cmake/data;/usr/local;/usr/X11R6;/usr/pkg;/opt
  
\nThe results will be copied to your clipboard if xclip is installed.
```

And, maybe #6374 is related to this.

**Comment by vectorijk** [comment]
I encounter the same issue when using 11.4.0
gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)
```
-- Running vcpkg install - done
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
```

**Comment by yma11** [comment]
@dcoliversun Thanks for reminder.
