### ISSUE TITLE
[VL] Performance regression since 4.12

### ISSUE THREAD

**Issue by ulysses-you** [apache/incubator-gluten#5548]
### Backend

VL (Velox)

### Bug description

[4.12 benckmark](https://github.com/apache/incubator-gluten/pull/5388#issuecomment-2052637866)
<img width="835" alt="image" src="https://github.com/apache/incubator-gluten/assets/12025282/08632427-ea87-44ea-8205-eb1ca6976c82">

[4.11 benchmark](https://github.com/apache/incubator-gluten/pull/5340#issuecomment-2050662530)
<img width="817" alt="image" src="https://github.com/apache/incubator-gluten/assets/12025282/932ae702-161c-4af6-aae2-f79fc39aaaa5">

[4.13 benchmark](https://github.com/apache/incubator-gluten/pull/5390#issuecomment-2053730821)
<img width="815" alt="image" src="https://github.com/apache/incubator-gluten/assets/12025282/8f2f436c-4654-4847-8253-ccaddbbaff51">

### Spark version

None

**Comment by zhztheplayer** [comment]
Is this related to known issue https://github.com/apache/incubator-gluten/pull/5401?

**Comment by zhli1142015** [comment]
Yes, they are same issue

**Comment by ulysses-you** [comment]
@zhztheplayer @zhli1142015  Is any updating about this issue ? thank you

**Comment by zhli1142015** [comment]
I submited a PR to make the number drop ~30s, please see https://github.com/facebookincubator/velox/issues/9732 . still looking more.

Thanks.

**Comment by ulysses-you** [comment]
thank you @zhli1142015  it seems the regression is almost gone . I close this issue.
