### ISSUE TITLE
nproc command in compile.sh isn't compatible with MacOS

### ISSUE THREAD

**Issue by NEUpanning** [apache/incubator-gluten#5559]
### Problem description

incubator-gluten/cpp/compile.sh script use `nproc` command to get the number of processing units available but MacOS dosen't support this comand. Here is the [code](https://github.com/apache/incubator-gluten/blob/main/cpp/compile.sh#L33).

**Comment by NEUpanning** [comment]
I would like to resolve this issue. We could get the number of processing units available like this code 
```
if [[ "$(uname)" == "Darwin" ]]; then
    physical_cpu_cores=$(sysctl -n hw.physicalcpu)
    ignore_cores=2
    if [ "$physical_cpu_cores" -gt "$ignore_cores" ]; then
        NPROC=${NPROC:-$(($physical_cpu_cores - $ignore_cores))}
    else
        NPROC=${NPROC:-$physical_cpu_cores}
    fi
else
    NPROC=${NPROC:-$(nproc --ignore=2)}
fi
```

**Comment by PHILO-HE** [comment]
Yes, you can fix it like https://github.com/apache/incubator-gluten/blob/main/dev/builddeps-veloxbe.sh#L37. Thanks!

**Comment by NEUpanning** [comment]
Thanks for your reply. I'll open a pull request for this issue.

**Comment by NEUpanning** [comment]
@PHILO-HE I opened [PR](https://github.com/apache/incubator-gluten/pull/5560) for this issue. Could you take a look? Thanks.

**Comment by ulysses-you** [comment]
In general, we can use nproc on macOS by `brew install coreutils`.
