### ISSUE TITLE
[VL] TPCDS bloom filter all fallbacked

### ISSUE THREAD

**Issue by Yohahaha** [apache/incubator-gluten#5577]
### Backend

VL (Velox)

### Bug description

After https://github.com/apache/incubator-gluten/pull/5435, all bloom filter are fallbacked, I wonder is expected? @zhztheplayer @zhouyuan 

### Spark version

None

### Relevant logs

```bash
4/04/29 17:55:16 WARN [benchmark runner] FilterExecTransformer: Validation failed with exception for plan: FilterExecTransformer, due to: Not supported to map spark function name to substrait function name: might_contain(Subquery subquery#68920, [id=#161001], xxhash64(d_week_seq#28, 42)), class name: BloomFilterMightContain.
24/04/29 17:55:16 WARN [benchmark runner] GlutenFallbackReporter: Validation failed for plan: Filter[QueryId=63], due to: Not supported to map spark function name to substrait function name: might_contain(Subquery subquery#68920, [id=#161001], xxhash64(d_week_seq#28, 42)), class name: BloomFilterMightContain..
24/04/29 17:55:16 WARN [benchmark runner] FilterExecTransformer: Validation failed with exception for plan: FilterExecTransformer, due to: Not supported to map spark function name to substrait function name: might_contain(Subquery subquery#68923, [id=#161014], xxhash64(d_week_seq#28, 42)), class name: BloomFilterMightContain.
24/04/29 17:55:16 WARN [benchmark runner] GlutenFallbackReporter: Validation failed for plan: Filter[QueryId=63], due to: Not supported to map spark function name to substrait function name: might_contain(Subquery subquery#68923, [id=#161014], xxhash64(d_week_seq#28, 42)), class name: BloomFilterMightContain..
24/04/29 17:55:16 WARN [subquery-27] RegularHashAggregateExecTransformer: Validation failed with exception for plan: RegularHashAggregateExecTransformer, due to: not currently supported: bloom_filter_agg(_pre_190#69003L, 335, 8990, 0, 0).
24/04/29 17:55:16 WARN [subquery-26] RegularHashAggregateExecTransformer: Validation failed with exception for plan: RegularHashAggregateExecTransformer, due to: not currently supported: bloom_filter_agg(_pre_189#69001L, 335, 8990, 0, 0).
24/04/29 17:55:16 WARN [subquery-27] GlutenFallbackReporter: Validation failed for plan: ObjectHashAggregate[QueryId=63], due to: not currently supported: bloom_filter_agg(_pre_190#69003L, 335, 8990, 0, 0).; not currently supported: bloom_filter_agg(_pre_190#69003L, 335, 8990, 0, 0)..
24/04/29 17:55:16 WARN [subquery-26] GlutenFallbackReporter: Validation failed for plan: ObjectHashAggregate[QueryId=63], due to: not currently supported: bloom_filter_agg(_pre_189#69001L, 335, 8990, 0, 0).; not currently supported: bloom_filter_agg(_pre_189#69001L, 335, 8990, 0, 0)..
```

**Comment by zhouyuan** [comment]
@Yohahaha hi yang, no, this is not expected. Hongze is still refactoring on the RAS part if i understand correctly

thanks,
-yuan

**Comment by Yohahaha** [comment]
> @Yohahaha hi yang, no, this is not expected. Hongze is still refactoring on the RAS part if i understand correctly
> 
> thanks,
> -yuan

thank you for the reply, I have not enable RAS yet.

**Comment by Yohahaha** [comment]
I'm curious why golden file check is passed when there is fallback? cc @ulysses-you

**Comment by ulysses-you** [comment]
For now, golden files only cover tpch.. tpcds is on the way cc @zwangsheng

**Comment by zhouyuan** [comment]
@ulysses-you currently the tests are using scale factor 1 and I find BHJ are always used. We may need to increase the scale factor or do more configurations to get a more meaningful TPCDS plan

**Comment by liujiayi771** [comment]
@ulysses-you @zhouyuan And it is better to use partition tables for test.

**Comment by ulysses-you** [comment]
@zhouyuan it should be ok, the golden files have checked both shuffled hash join(by disabling autoBroadcastThreshold) and broadcast hash join.

@liujiayi771 yeah, I think it would be more meaningful to use partitioned table to generate tpcds golden files.

**Comment by zhztheplayer** [comment]
Oops, this was accidentally closed while I was merging the pr. @Yohahaha please let me know if the issue still exists. Thanks.

**Comment by Yohahaha** [comment]
> Oops, this was accidentally closed while I was merging the pr. @Yohahaha please let me know if the issue still exists. Thanks.

This issue has been fixed, thank you!
