### ISSUE TITLE
[VL] Random memory leak

### ISSUE THREAD

**Issue by zhli1142015** [apache/incubator-gluten#5611]
### Backend

VL (Velox)

### Bug description

From CI pipeline, there are some failures caused by random memory leak.
https://github.com/apache/incubator-gluten/actions/runs/8964181078/job/24615572223?pr=5602

https://github.com/apache/incubator-gluten/pull/5456#issuecomment-2095095918

24/05/06 05:55:29 WARN NativeMemoryManager: WholeStageIterator Reservation listener org.apache.gluten.memory.nmm.ManagedReservationListener@514e3e4b still reserved non-zero bytes, which may cause memory leak, size: 8.0 MiB. 
24/05/06 05:55:29 ERROR Executor: Exception in task 0.0 in stage 209.0 (TID 209)
org.apache.spark.SparkException: Managed memory leak detected; size = 8388608 bytes, task 0.0 in stage 209.0 (TID 209)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:516)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1500)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

### Spark version

None

**Comment by zhli1142015** [comment]
cc @zhouyuan, @zhztheplayer   and @FelixYBW

**Comment by FelixYBW** [comment]
Thank you for reporting. @zhztheplayer can you take a look?

**Comment by Yohahaha** [comment]
I think this function is the issue.
https://github.com/apache/incubator-gluten/blob/fea47053c9716ad1cc2433403312b348889ca959/cpp/velox/memory/VeloxMemoryManager.cc#L94-L108

**Comment by zhztheplayer** [comment]
> I think this function is the issue.
> 
> https://github.com/apache/incubator-gluten/blob/fea47053c9716ad1cc2433403312b348889ca959/cpp/velox/memory/VeloxMemoryManager.cc#L94-L108

Thanks for catching! I didn't check if it's related to this issue but it looks like my mistake missing a return statement in the code you mentioned.

Would you like to make a fix for it? Thanks!

**Comment by Yohahaha** [comment]
> > I think this function is the issue.
> > https://github.com/apache/incubator-gluten/blob/fea47053c9716ad1cc2433403312b348889ca959/cpp/velox/memory/VeloxMemoryManager.cc#L94-L108
> 
> Thanks for catching! I didn't check if it's related to this issue but it looks like my mistake missing a return statement in the code you mentioned.
> 
> Would you like to make a fix for it? Thanks!

I have fixed and verified in our internal case, but there exists another issue for high peak memory https://github.com/apache/incubator-gluten/issues/5630.
