### ISSUE TITLE
Add new added Spark3.5 UTs in Gluten

### ISSUE THREAD

**Issue by yma11** [apache/incubator-gluten#5622]
### Description

In Spark 3.5, there are some new added UTs vs Spark3.4 which haven't been added in Gluten yet. We need port them for better validation coverage.

**Comment by FelixYBW** [comment]
Are 3.5 UT all passed?

**Comment by yma11** [comment]
Not all. There are some UTs about row index metadata column failed. This feature is under development, refer [PR](https://github.com/facebookincubator/velox/pull/9174). We will revisit them once it's ready.
