### ISSUE TITLE
[VL] Unexpected memory issue found in CI

### ISSUE THREAD

**Issue by Yohahaha** [apache/incubator-gluten#5673]
### Backend

VL (Velox)

### Bug description

```
W20240509 07:32:15.819299 59531 MemoryAllocator.cpp:186] [MEM] Exceeded memory reservation limit when reserve 1 new pages when allocate 1 pages
E20240509 07:32:15.819386 59531 Executor.cpp:31] ThreadPoolExecutor: func threw unhandled gluten::GlutenException: Unexpected: Failed to reserve 1048576 bytes although there is enough space, free bytes: 1048576
```

https://github.com/apache/incubator-gluten/actions/runs/9013102975/job/24763373229?pr=5672

### Spark version

None

**Comment by Yohahaha** [comment]
We can give `memoryPoolInitCapacity` a proper default value(32MB) to decrease memory request times, and may relieve concurrent memory request from DBI.

And could combine `memoryPoolTransferCapacity_` with `spark.gluten.memory.reservationBlockSize` then remove AllocationListener's reservation compute logic.

**Comment by FelixYBW** [comment]
@zhztheplayer
