### ISSUE TITLE
Can I install Gluten in AWS EMR? Unsupport linux distribution: amzn

### ISSUE THREAD

**Issue by astarrr** [apache/incubator-gluten#5689]
### Description

Hello,
I am trying to install Gluten on EMR but I got this error

```
+++ SUPPORT_END=2025-06-30
++ echo 2
+ local LINUX_VERSION_ID=2
+ sed -i 's/^  ninja -C "${BINARY_DIR}" install/  sudo ninja -C "${BINARY_DIR}" install/g' scripts/setup-helper-functions.sh
+ sed -i 's/-mavx2 -mfma -mavx -mf16c -mlzcnt -std=c++17/-march=native -std=c++17 -mno-avx512f/g' scripts/setup-helper-functions.sh
+ [[ amzn == \u\b\u\n\t\u ]]
+ [[ amzn == \d\e\b\i\a\n ]]
+ [[ amzn == \p\o\p ]]
+ [[ amzn == \c\e\n\t\o\s ]]
+ [[ amzn == \a\l\i\n\u\x ]]
+ [[ amzn == \t\e\n\c\e\n\t\o\s ]]
+ echo 'Unsupport linux distribution: amzn'
Unsupport linux distribution: amzn
+ exit 1
```

As far as I understand, Gluten is supported only on CentOS and Ubuntu. Is there any AMI (Amazon Machine Image) based on CentOS or Ubuntu that I can spin-up in my cluster?

Thanks,

**Comment by PHILO-HE** [comment]
@astarrr, I guess it can work on your centos-like or ubuntu-like OS after a few code changes are made. Currently, we hard-coded the supported OS. To let the script for centos or ubuntu be called for your OS, you can add some code here: https://github.com/apache/incubator-gluten/blob/main/ep/build-velox/src/build_velox.sh#L274.
