### ISSUE TITLE
[VL] Reuse native build artifact for different spark version to save resources and time

### ISSUE THREAD

**Issue by Yohahaha** [apache/incubator-gluten#5721]
### Description

native build artifact (velox and gluten cpp) is common for different spark version, we can reuse it and trigger java module when success.

cc @zhouyuan @PHILO-HE

**Comment by PHILO-HE** [comment]
We are still trying to re-use static linked libraries, which is built out in one OS, but can be used in other OS. I guess there are still some issues under fixing. cc @zhouyuan

**Comment by PHILO-HE** [comment]
@Yohahaha, we have an internal discussion. There are still a gap to re-use static linked libraries across different OS. I will add a cache in CI to save time, as you proposed. Thanks!
