### ISSUE TITLE
spillTime_ is been calculated twice?

### ISSUE THREAD

**Issue by XinShuoWang** [apache/incubator-gluten#5724]
I think it is enough to use `ScopedTimer timer(&spillTime_);` to calculate spillTime. Why do we need `spillTime_ += payload->getWriteTime();` ? The time consumption of `ScopedTimer` should include `payload->getWriteTime()`, right?

https://github.com/apache/incubator-gluten/blob/74f3061d88ce3155daca921c23266801533e7710/cpp/core/shuffle/LocalPartitionWriter.cc#L47

https://github.com/apache/incubator-gluten/blob/74f3061d88ce3155daca921c23266801533e7710/cpp/core/shuffle/LocalPartitionWriter.cc#L63

**Comment by XinShuoWang** [comment]
@marin-ma Is my guess right?

**Comment by marin-ma** [comment]
@XinShuoWang Thanks for the catch! I'll fix it soon.
