### ISSUE TITLE
Reduce GitHub Action usage according to ASF project allowance

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-gluten#5765]
### Problem description

https://infra.apache.org/github-actions-policy.html

### System information

![image](https://github.com/apache/incubator-gluten/assets/8326978/7ecef50a-4b01-491d-8f9b-38286221b27a)

### CMake log

```bash
-
```

**Comment by FelixYBW** [comment]
@zhouyuan should we take immediate action to withdraw some CI to internal machine firstly?

**Comment by zhouyuan** [comment]
@FelixYBW yes, we are now moving back some of the tests to our internal CI
and also is re-constructing the CI to reduce the usage
https://github.com/apache/incubator-gluten/pull/5768

thanks
-yuan

**Comment by zhouyuan** [comment]
https://github.com/apache/incubator-gluten/pull/5780

**Comment by PHILO-HE** [comment]
One thought is, we can make some PR-triggered jobs only run nightly, such as Java-17 tests, etc., assuming they rarely fail.

**Comment by yaooqinn** [comment]
feel free to close this if you guys believe it's resolved

**Comment by zhouyuan** [comment]
closing as the GHA usage is below 25FT.
