### ISSUE TITLE
Error when intermedia data type is not a struct type

### ISSUE THREAD

**Issue by liujp** [apache/incubator-gluten#5840]
### Backend

VL (Velox)

### Bug description

when define an intermediate type of the uadf without Row as:
<img width="562" alt="image" src="https://github.com/apache/incubator-gluten/assets/11934146/ed0cb8d9-cd0c-4b58-9de1-ddfc88538528">

and register a UDAF signature:
<img width="696" alt="image" src="https://github.com/apache/incubator-gluten/assets/11934146/aaeb4f81-1481-4e6d-be55-b217957ec72c">
<img width="995" alt="image" src="https://github.com/apache/incubator-gluten/assets/11934146/4c26c0f8-e3f5-4019-9228-8b742b06369d">

but an error occurs:
<img width="1533" alt="image" src="https://github.com/apache/incubator-gluten/assets/11934146/e2ce31de-22ed-44c4-a68d-1a7af7644629">

<img width="746" alt="image" src="https://github.com/apache/incubator-gluten/assets/11934146/c1db421e-af02-4c00-a69d-8c800b9dc4dc">

### Spark version

None

**Comment by liujp** [comment]
@marin-ma

**Comment by FelixYBW** [comment]
Is the root cause that UDF doesn't support struct?

**Comment by liujp** [comment]
> Is the root cause that UDF doesn't support struct?

Multi-parameters in intermediate can be set in this way, but it is wried for users, when they want only to use a single type.
by the way, if the intermediate type is struct<XX_type>, the aggregate planNode can be transformed error.
