### ISSUE TITLE
[VL] Noisy wrong fallback message after case-class refactor

### ISSUE THREAD

**Issue by Yohahaha** [apache/incubator-gluten#5880]
### Backend

VL (Velox)

### Bug description

```
== Fallback Summary ==
(1) LocalTableScan: Gluten does not touch it or does not support it
(7) NoopLeaf: Gluten does not touch it or does not support it
(8) WriteFiles: Gluten does not touch it or does not support it

== Physical Plan ==
Execute InsertIntoHadoopFsRelationCommand (11)
+- VeloxColumnarWriteFiles (10)
   :- ^ WriteFilesExecTransformer (5)
   :  +- ^ InputIteratorTransformer (4)
   :     +- ^ InputAdapter (3)
   :        +- ^ RowToVeloxColumnar (2)
   :           +- ^ LocalTableScan (1)
   +- RowToVeloxColumnar (9)
      +- WriteFiles (8)
         +- NoopLeaf (7)
```

```
24/05/27 17:32:18 WARN [main] GlutenFallbackReporter: Validation failed for plan: Execute InsertIntoHadoopFsRelationCommand[QueryId=0], due to: at least one of its children has empty output; at least one of its children has empty output
```

Each huge refactoring of plan conversion framework bring new concepts for user/developer, and not only need lots time to understanding new code structure and new naming, but also introduce misleading fallback messages.

In above case, I need to check code and UI more carefully to ensure the fallback log from GlutenFallbackReporter is wrong, but I really dont want to.

https://github.com/apache/incubator-gluten/pull/5698
https://github.com/apache/incubator-gluten/pull/5480

### Spark version

None

**Comment by zhztheplayer** [comment]
I see there is already a [list](https://github.com/apache/incubator-gluten/blob/12fdb7029a4921ff035c8a979c1580447d0acb72/gluten-core/src/main/scala/org/apache/spark/sql/execution/GlutenImplicits.scala#L102) can be used to add exclusions. I can help update that list if you think is needed.

**Comment by Yohahaha** [comment]
> I see there is already a [list](https://github.com/apache/incubator-gluten/blob/12fdb7029a4921ff035c8a979c1580447d0acb72/gluten-core/src/main/scala/org/apache/spark/sql/execution/GlutenImplicits.scala#L102) can be used to add exclusions. I can help update that list if you think is needed.

that's great, thank you!

**Comment by FelixYBW** [comment]
Can we create an exception for each fallback reason? then put the message in the exception? @zhztheplayer Let's have a sync on this.

**Comment by zhztheplayer** [comment]
A proposed fix was included in https://github.com/apache/incubator-gluten/pull/5698. @Yohahaha
