### ISSUE TITLE
[CH] DIff result for get_json_object to get null value

### ISSUE THREAD

**Issue by exmy** [apache/incubator-gluten#5981]
### Backend

CH (ClickHouse)

### Bug description

`select get_json_object('{"t": null}', '$.t') is null;`

spark result: true

gluten result: false

### Spark version

None

**Comment by lgbo-ustc** [comment]
the result from `JSON_QUERY` in `CH` is a string value

**Comment by lgbo-ustc** [comment]
I will fix it
