### ISSUE TITLE
[VL] Support HiveFileFormat writes using Velox backend 

### ISSUE THREAD

**Issue by surnaik** [apache/incubator-gluten#6026]
### Description

Currently, HiveFileFormat writes fallback to Spark, writes of HiveFileFormat can be supported when underlying file format is of type Parquet.

cc: @ulysses-you @PHILO-HE

**Comment by ulysses-you** [comment]
@surnaik Do you have a plan to work on this ? I think we can add one more config to support transform HiveFileFormat.

**Comment by FelixYBW** [comment]
We should already support hive write if file type is parquet. @JkSelf & @yma11

**Comment by JkSelf** [comment]
@FelixYBW HiveFileFormat is only supported in spark 32 and 33.  spark 3.4 and 3.5 will fallback to vanilla spark. Because many hive configurations is not supported in velox. We may need to support in velox firstly.

**Comment by FelixYBW** [comment]
> @FelixYBW HiveFileFormat is only supported in spark 32 and 33. spark 3.4 and 3.5 will fallback to vanilla spark. Because many hive configurations is not supported in velox. We may need to support in velox firstly.

Do you have a list of such configuration?

**Comment by JkSelf** [comment]
@FelixYBW The following is the spark sql hive configurations in [SQLConf.scala](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/internal/SQLConf.scala).

```
spark.sql.hive.advancedPartitionPredicatePushdown.enabled
spark.sql.hive.dropPartitionByName.enabled
spark.sql.hive.metastorePartitionPruning
spark.sql.hive.metastorePartitionPruningInSetThreshold
spark.sql.hive.metastorePartitionPruningFallbackOnException
spark.sql.hive.metastorePartitionPruningFastFallback
spark.sql.hive.manageFilesourcePartitions
spark.sql.hive.filesourcePartitionFileCacheSize
spark.sql.hive.caseSensitiveInferenceMode
spark.sql.hive.tablePropertyLengthThreshold
spark.sql.hive.convertCTAS 
```

**Comment by surnaik** [comment]
> @FelixYBW The following is the spark sql hive configurations in [SQLConf.scala](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/internal/SQLConf.scala).
> 
> ```
> spark.sql.hive.advancedPartitionPredicatePushdown.enabled
> spark.sql.hive.dropPartitionByName.enabled
> spark.sql.hive.metastorePartitionPruning
> spark.sql.hive.metastorePartitionPruningInSetThreshold
> spark.sql.hive.metastorePartitionPruningFallbackOnException
> spark.sql.hive.metastorePartitionPruningFastFallback
> spark.sql.hive.manageFilesourcePartitions
> spark.sql.hive.filesourcePartitionFileCacheSize
> spark.sql.hive.caseSensitiveInferenceMode
> spark.sql.hive.tablePropertyLengthThreshold
> spark.sql.hive.convertCTAS 
> ```

Any idea which of these are not supported currently by velox?

**Comment by surnaik** [comment]
Looking deeper into these configs, I think we can support writes when file is of type parquet, all these affect HiveFileFormat read, but write doesn't seem to be affected by these configs, all of these seem to affect reads only. 
What do you think @JkSelf / @ulysses-you

**Comment by ulysses-you** [comment]
@surnaik I think we can move ahead if there is no block or some minor known issue which can fallback.

**Comment by surnaik** [comment]
Thanks, working on this
