### ISSUE TITLE
[CH] Function `lag` result diff from valina spark

### ISSUE THREAD

**Issue by KevinyhZou** [apache/incubator-gluten#6082]
### Backend

CH (ClickHouse)

### Bug description

test table schema (id bigint, d string), with test data (137438953483, '2024-05'), do the query `select d, lag(d,1,d) over (partition by id order by d) from test_tbl3 `

gluten result
| 2024-05  | NULL   

and valina  result
2024-05  2024-05

### Spark version

Spark-3.3.x

**Comment by lgbo-ustc** [comment]
Let it fallback at first.
