### ISSUE TITLE
[VL] folly build error

### ISSUE THREAD

**Issue by lihao712** [apache/incubator-gluten#6087]
### Problem description

when I build and install Gluten with Velox backend with config enable_vcpkg=ON,
run step by step in sciript like this:
f [ "$ENABLE_VCPKG" = "ON" ]; then
    # vcpkg will install static depends and init build environment
    envs="$("$GLUTEN_DIR/dev/vcpkg/init.sh")"
    eval "$envs"
fi

## build velox
concat_velox_param
cd $GLUTEN_DIR/ep/build-velox/src
./get_velox.sh --enable_hdfs=$ENABLE_HDFS --build_protobuf=$BUILD_PROTOBUF --enable_s3=$ENABLE_S3 --enable_gcs=$ENABLE_GCS --enable_abfs=$ENABLE_ABFS $VELOX_PARAMETER
# When BUILD_TESTS is on for gluten cpp, we need turn on VELOX_BUILD_TEST_UTILS via build_test_utils.
./build_velox.sh --run_setup_script=xxxxxx
                 
when I run (envs="$("$GLUTEN_DIR/dev/vcpkg/init.sh")"  ) in vcpkg install folly
it throw error  :

Installing 211/253 folly:x64-linux-avx...
Building folly[core,lz4,lzma,snappy,zlib,zstd]:x64-linux-avx...
-- [OVERLAY] Loading triplet configuration from: /root/gluten-test/incubator-gluten-1.1.1/dev/vcpkg/triplets/x64-linux-avx.cmake
-- Installing port from location: /root/gluten-test/incubator-gluten-1.1.1/dev/vcpkg/./ports/folly
-- Using cached facebook-folly-v2023.12.04.00.tar.gz.
-- Cleaning sources at /root/gluten-test/incubator-gluten-1.1.1/dev/vcpkg/.vcpkg/buildtrees/folly/src/3.12.04.00-bebeab2c8d.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /root/gluten-test/incubator-gluten-1.1.1/dev/vcpkg/.vcpkg/downloads/facebook-folly-v2023.12.04.00.tar.gz
-- Applying patch reorder-glog-gflags.patch
-- Applying patch disable-non-underscore-posix-names.patch
-- Applying patch boost-1.70.patch
-- Applying patch fix-windows-minmax.patch
-- Applying patch fix-deps.patch
-- Using source at /root/gluten-test/incubator-gluten-1.1.1/dev/vcpkg/.vcpkg/buildtrees/folly/src/3.12.04.00-bebeab2c8d.clean
-- Found external ninja('1.11.1').
-- Configuring x64-linux-avx
-- Building x64-linux-avx-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: /root/gluten-test/incubator-gluten-1.1.1/dev/vcpkg/.vcpkg/downloads/tools/cmake-3.27.1-linux/cmake-3.27.1-linux-x86_64/bin/cmake --build . --config Release --target install -- -v -j57
    Working Directory: /root/gluten-test/incubator-gluten-1.1.1/dev/vcpkg/.vcpkg/buildtrees/folly/x64-linux-avx-rel
    See logs for more information:
      /root/gluten-test/incubator-gluten-1.1.1/dev/vcpkg/.vcpkg/buildtrees/folly/install-x64-linux-avx-rel-out.log

Call Stack (most recent call first):
  /root/gluten-test/incubator-gluten-1.1.1/dev/vcpkg/vcpkg_installed/x64-linux-avx/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  /root/gluten-test/incubator-gluten-1.1.1/dev/vcpkg/vcpkg_installed/x64-linux-avx/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  /root/gluten-test/incubator-gluten-1.1.1/dev/vcpkg/ports/folly/portfile.cmake:73 (vcpkg_cmake_install)
  scripts/ports.cmake:168 (include)

error: building folly:x64-linux-avx failed with: BUILD_FAILED
Elapsed time to handle folly:x64-linux-avx: 27 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.      

how can I solve this problem?        

### System information

Velox System Info v0.0.2
Commit: Not in a git repo.
CMake Version: 2.8.12
System: Linux-4.18.0-2.4.3.3.kwai.x86_64
Arch: x86_64
C++ Compiler: /opt/rh/devtoolset-7/root/usr/bin/c++
C++ Compiler Version: 7.3.1
C Compiler: /opt/rh/devtoolset-7/root/usr/bin/cc
C Compiler Version: 7.3.1
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local

**Comment by lihao712** [comment]
when I update cmake from 2.8.12 to 3.27.0  compiling error as last show

**Comment by PHILO-HE** [comment]
Could you paste some key message in `/root/gluten-test/incubator-gluten-1.1.1/dev/vcpkg/.vcpkg/buildtrees/folly/install-x64-linux-avx-rel-out.log`?

**Comment by lihao712** [comment]
> Could you paste some key message in `/root/gluten-test/incubator-gluten-1.1.1/dev/vcpkg/.vcpkg/buildtrees/folly/install-x64-linux-avx-rel-out.log`?

I compile gluten in non-docker environment, let me use docker to build release jar
