### ISSUE TITLE
[CH]  Native parquet writer doesn't generate page index 

### ISSUE THREAD

**Issue by lgbo-ustc** [apache/incubator-gluten#6147]
### Description

Compare to vanilla, there is no page index in the parquet files from gluten's native parquet writer.
```c++
 auto page_index_reader = file_reader.GetPageIndexReader()->RowGroup(row_group);
```
the `page_index_reader` is `nullptr`.

**Comment by zhanglistar** [comment]
Seems that arrow does not support page index for now.

**Comment by lgbo-ustc** [comment]
page index is disable at default
![image](https://github.com/apache/incubator-gluten/assets/2599447/61f9e9bb-7d72-46b1-8a45-2624d00ad990)

**Comment by lgbo-ustc** [comment]
Lastest ch have supported at default
