### ISSUE TITLE
[VL] Simplify JniLibLoader

### ISSUE THREAD

**Issue by zhztheplayer** [apache/incubator-gluten#6148]
### Description

Overtime we find that `JniLibLoader` might be over-designed. Given that when a shared library is unable to be loaded, Gluten usually just refuses to do anything (e.g., just crashes). Thus ideally we load all the libraries needed, or we just raise fatal error.

`JniLoader` implemented a transactional loading mechanism that supports loading all the specified libraries together and with a rarely used "roll back" API. These stuffs may be the first priority to remove in the topic to simplify code.

**Comment by ArnavBalyan** [comment]
Hi @zhztheplayer I would like to work on this. Can you give some more clarity, we want to get rid of the transactional loading?

**Comment by zhztheplayer** [comment]
> we want to get rid of the transactional loading?

I think it doesn't make any actual difference with loading the libs one by one. Probably we can test and prove. The issue is somewhat benign as nevertheless we don't have much code in `JniLibLoader.java`. Anyway, feel free to take if you want. Thanks.

**Comment by ArnavBalyan** [comment]
I see thanks! I can do some testing and raise changes
