### ISSUE TITLE
[VL] Add CPP unit test for UDF

### ISSUE THREAD

**Issue by NEUpanning** [apache/incubator-gluten#6195]
### Description

The UDF examples only have TestMyUDF.cc for testing whether UDF is registered and VeloxUdfSuite.scala for integration test. In our practice, we need compile gluten java code for testing after changing the UDF cpp code, which takes a lot of time. Maybe we should add unit test like [Velox functions test](https://facebookincubator.github.io/velox/develop/scalar-functions.html#testing) so we can save the time for doing scala test.

**Comment by NEUpanning** [comment]
@marin-ma How do you think? Thanks!

**Comment by marin-ma** [comment]
@NEUpanning +1 Thanks for the proposal. We have one simple executable here to test the UDF registration https://github.com/apache/incubator-gluten/blob/main/cpp/velox/udf/examples/TestMyUDF.cc Not sure if it would be helpful to create the UDF CPP test framework.

Would you like to help on implementing this?

**Comment by NEUpanning** [comment]
@marin-ma Thanks for your reply. I would like to implement this.
