### ISSUE TITLE
[VL] No extra SortExec needed before WindowExec if window type is `sort`

### ISSUE THREAD

**Issue by WangGuangxin** [apache/incubator-gluten#6202]
### Backend

VL (Velox)

### Bug description

When `spark.gluten.sql.columnar.backend.velox.window.type` is set to `sort`, there should be no extra `SortExec` before `WindowExec` in plan.

### Spark version

None

**Comment by FelixYBW** [comment]
Can you list such a query as example?

**Comment by JkSelf** [comment]
In order to remove the duplicated sort operator, we implement the streaming window for spark in velox. Why need to set the sort based window in your use case? Can you share more about your use cases? Thanks.

**Comment by WangGuangxin** [comment]
> Can you list such a query as example?

Any window query with following conf set to `sort`
--conf spark.gluten.sql.columnar.backend.velox.window.type=sort

for example (lineitem from tpch)
```
select row_number() over (partition by l_suppkey order by l_orderkey) from lineitem 
```


When we set `spark.gluten.sql.columnar.backend.velox.window.type=sort`, velox will use sort based window builder, so there is no need to sort outside `WindowExec` operator, right? 

![image](https://github.com/apache/incubator-gluten/assets/1312321/614544e0-0bd4-4e28-8bcb-785dcae3f8d9)

cc @JkSelf

**Comment by WangGuangxin** [comment]
> In order to remove the duplicated sort operator, we implement the streaming window for spark in velox. Why need to set the sort based window in your use case? Can you share more about your use cases? Thanks.

@JkSelf We are just doing some investigating.  Both `SortExec`  and `WindowExec` need lots of C2R and R2C within the implemention, especially spill occured.  We are hard to do something for `Sort` outside `Window` , but for `Sort` within `Window` ( aka sort based window), maybe we can eliminate some C2R and C2R.  
Do you have any suggestion?

**Comment by FelixYBW** [comment]
> > In order to remove the duplicated sort operator, we implement the streaming window for spark in velox. Why need to set the sort based window in your use case? Can you share more about your use cases? Thanks.
> 
> @JkSelf We are just doing some investigating. Both `SortExec` and `WindowExec` need lots of C2R and R2C within the implemention, especially spill occured. It is hard to do something for `Sort` outside `Window` , but for `Sort` within `Window` ( aka sort based window), maybe we can eliminate some C2R and C2R. Do you have any suggestion?

Why do you need C2R, R2C?
