### ISSUE TITLE
[VL] Results are mismatch with vanilla Spark when use regexp_replace('a{bc', '\\{', '\\[')

### ISSUE THREAD

**Issue by kecookier** [apache/incubator-gluten#6224]
### Backend

VL (Velox)

### Bug description

```sql
spark-sql> set spark.sql.optimizer.excludedRules=org.apache.spark.sql.catalyst.optimizer.ConstantFolding;
spark-sql> select regexp_replace('a{bc', '\\{', '\\[');

vanilla get
a[bc

gluten get
abc
```

### Spark version

Spark-3.2.x

### System information

Velox System Info v0.0.2
Commit: 3a459abad5af1a8cc268c349bc3813249511768c
CMake Version: 3.22.0
System: Linux-3.10.0-862.mt20190308.130.el7.x86_64
Arch: x86_64
CPU Name: Model name:            Intel(R) Xeon(R) Platinum 8255C CPU @ 2.50GHz
C++ Compiler: /opt/rh/devtoolset-9/root/usr/bin/c++
C++ Compiler Version: 9.3.1
C Compiler: /opt/rh/devtoolset-9/root/usr/bin/cc
C Compiler Version: 9.3.1
CMake Prefix Path: /usr/local;/usr;/;/usr/local/cmake;/usr/local;/usr/X11R6;/usr/pkg;/opt

**Comment by gaoyangxiaozhu** [comment]
thanks @kecookier I will take a look when have time

**Comment by kecookier** [comment]
> thanks @kecookier do you will help fix the issue ?

Yes, I will work on this issue.

**Comment by wang-zhun** [comment]
@kecookier I also encountered this problem. Although it's not resolved, I can provide some information.

##### present situation
```
--- Query
with tb as (
select
    name
FROM Values
    ('12234') people (name)
)
select regexp_replace(name, '22', '\\|') c1, 'gluten-spark' c2 from (select /*+ repartition(2) */ * from tb)
union
select regexp_replace(name, '22', '\\|') c1, 'vanilla-spark' c2 from tb

-- Result
c1            c2
1|34      vanilla-spark
134       gluten-spark
```

##### [Gluten Velox RE2](https://github.com/oap-project/velox/blob/3b138e5fd1ae6ca3a17f3bfdb5ff062031f487d4/velox/functions/sparksql/RegexFunctions.cpp#L133)
```
1. code
#include <iostream>
#include <re2/re2.h>

int main() {
    std::string input = "12234";
    RE2 pattern("22");
    std::string replacement = "\\|";
    int replacements = RE2::GlobalReplace(&input, pattern, replacement);
    std::cout << "Modified string: " << input << std::endl;
    return 0;
}

2. output：
re2/re2.cc:1059: invalid rewrite pattern: \|
Modified string: 134

3. compile：
g++ -o example example.cpp -L/usr/local/lib -lre2 -Wl,-rpath,/usr/local/lib
```

##### [Spark java.util.regex](https://github.com/apache/spark/blob/930422389352b8349e5a845c8cae9993d30dce17/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/regexpExpressions.scala#L735)
```
1. code
    import java.util.regex.Matcher
    import java.util.regex.Pattern

    val input = "12234"
    val pattern: Pattern = Pattern.compile("22")
    val replacement = "\\|"
    val matcher: Matcher = pattern.matcher(input)
    val result = matcher.replaceAll(replacement)
    println(s"Modified string: $result")

2. output：
Modified string: 1|34
```

**Comment by kecookier** [comment]
@wang-zhun Sorry for the late reply, and thank you for the information. I have a work-in-progress PR that will fix this issue.

**Comment by PHILO-HE** [comment]
Posting code where re2 error happens for replacement string with "\\\\": https://github.com/google/re2/blob/6dcd83d60f7944926bfd308cc13979fc53dd69ca/re2/re2.cc#L1053.

While [java.util.regex.Matcher](https://github.com/frohoff/jdk8u-dev-jdk/blob/master/src/share/classes/java/util/regex/Matcher.java#L812) views characters after "\\\\" as literal, i.e., using what it is after "\\\\".

Can we just change the replacement string to let Re2 do the correct replacement?

**Comment by kecookier** [comment]
@PHILO-HE  Apologies for the delayed response. This PR attempts to fix the mismatch problems in `regexp_replace`: https://github.com/facebookincubator/velox/pull/10981

**Comment by kecookier** [comment]
https://github.com/facebookincubator/velox/pull/10981  Already merged
