### ISSUE TITLE
[VL] Results are mismatch with vanilla Spark when using unix_timestamp(yyyy-MM-dd HH:mm:ss,SSS)

### ISSUE THREAD

**Issue by NEUpanning** [apache/incubator-gluten#6227]
### Backend

VL (Velox)

### Bug description

Results are mismatch with vanilla Spark setting "spark.sql.legacy.timeParserPolicy" to "LEGACY" when using unix_timestamp(yyyy-MM-dd HH:mm:ss,SSS).

create table sql:
```
CREATE TABLE tbl(a STRING) ;
insert into tbl values("2022-01-04 14:52:40.017")
```
gluten result:

```
select unix_timestamp(a) from tbl;
> NULL
```

spark3.5 result:

```
set spark.sql.legacy.timeParserPolicy=LEGACY;
select unix_timestamp(a) from tbl;
> 1641279160
```

### Spark version

Spark-3.5.x

**Comment by NEUpanning** [comment]
Resolved by [velox#11386](https://github.com/facebookincubator/velox/pull/11386)

**Comment by rui-mo** [comment]
Hi @NEUpanning, thanks for your contribution. Do we have any unit test in Gluten to ensure this issue has been fixed?

**Comment by NEUpanning** [comment]
@rui-mo Thanks for catching that. I've added unit tests in #7975
