### ISSUE TITLE
[CH] Diff result for upper('ır')

### ISSUE THREAD

**Issue by exmy** [apache/incubator-gluten#6244]
### Backend

VL (Velox)

### Bug description

`select upper('ır');`

gluten result: `ıR`
spark result: `IR`

https://clickhouse.com/docs/en/sql-reference/functions/string-functions#upperutf8
![image](https://github.com/apache/incubator-gluten/assets/18643308/cf9e5673-a33c-4860-a3fa-29557cd0997e)

### Spark version

None

**Comment by taiyang-li** [comment]
https://github.com/ClickHouse/ClickHouse/pull/65761

**Comment by taiyang-li** [comment]
<img width="470" alt="image" src="https://github.com/user-attachments/assets/cefde9c3-a70d-460a-91a3-b7f2ffa6abb6">
