### ISSUE TITLE
Rename transform-hint to fallback-hint

### ISSUE THREAD

**Issue by gaoyangxiaozhu** [apache/incubator-gluten#6246]
### Description

a follow up of this https://github.com/apache/incubator-gluten/pull/4731

**Comment by gaoyangxiaozhu** [comment]
@zhztheplayer  FYI, hey Hongze, do you have time do antoher patch for Rename transform-hint to fallback-hint, if not do you mind I help for the change ?

**Comment by zhztheplayer** [comment]
> @zhztheplayer FYI, hey Hongze, do you have time do antoher patch for Rename transform-hint to fallback-hint, if not do you mind I help for the change ?

Sounds great, please go ahead. Thank you for helping.
