### ISSUE TITLE
Online CI fail in setup java and maven stage

### ISSUE THREAD

**Issue by gaoyangxiaozhu** [apache/incubator-gluten#6299]
### Problem description

online CI fail 

@PHILO-HE / @zhouyuan  looks CI fail during maven and java setup stage, please help fix.
![image](https://github.com/apache/incubator-gluten/assets/9858245/b252d7c5-0e1c-47ef-ae46-677ac30e7b69)

Looks all recent active PRs fail due to this reason.

### System information

N/A

**Comment by gaoyangxiaozhu** [comment]
@PHILO-HE help fix.

**Comment by PHILO-HE** [comment]
It should have been fixed by https://github.com/apache/incubator-gluten/pull/6298.
