### ISSUE TITLE
[VL] Add Scala 2.13 support

### ISSUE THREAD

**Issue by zhztheplayer** [apache/incubator-gluten#6316]
### Description

To support compilation with `-P scala-2.13` which was added in patch https://github.com/apache/incubator-gluten/pull/6311 in Velox backend.

So far `-P backends-velox,scala-2.13` causes compile time error.

**Comment by surnaik** [comment]
@zhztheplayer if nobody is working on this, please let me know, I can add support for this. Thanks!

**Comment by zhztheplayer** [comment]
> @zhztheplayer if nobody is working on this, please let me know, I can add support for this. Thanks!

Sure, feel free to take. Thank you for helping.
