### ISSUE TITLE
Memoy leak in VeloxParquetDatasource

### ISSUE THREAD

**Issue by liujp** [apache/incubator-gluten#6430]
### Backend

VL (Velox)

### Bug description

in file VeloxParquetDatasource.cc
there is a data member in VeloxParquetDatasource and is likely not used.
<img width="809" alt="image" src="https://github.com/user-attachments/assets/218eec54-a344-41db-84d5-f7ac2bc41ebc">
 here the type_  doesn't hold memory from the cSchema, So the temp var cSchema should be released by ArrowSchemaRelease(&cSchema); 

as files:
<img width="873" alt="image" src="https://github.com/user-attachments/assets/688f9b1d-f53d-495f-a4ad-285a614880df">

@rui-mo

**Comment by rui-mo** [comment]
@liujp Thanks for your feedback. There is a leak indeed from my view. @JkSelf @zhztheplayer Do you have any input?

**Comment by zhztheplayer** [comment]
Thank you for reporting this.

My feeling is C schema's release could be done inside Velox's importing code. See various import code for languages from official Apache Arrow:

https://github.com/apache/arrow/blob/57ac40ca23ebcaa4d42ae808137033689d3be9b1/java/c/src/main/java/org/apache/arrow/c/Data.java#L246-L255
https://github.com/apache/arrow/blob/57ac40ca23ebcaa4d42ae808137033689d3be9b1/csharp/src/Apache.Arrow/C/CArrowSchemaImporter.cs#L128C25-L139

They all release the schema after finishing importing.

**Comment by JkSelf** [comment]
@liujp It seems https://github.com/apache/incubator-gluten/blob/main/cpp/velox/operators/writer/VeloxParquetDatasource.cc#L56-L62 code is no needed. Can you help to delete? Thanks.
