### ISSUE TITLE
vcpkg setup-build-depends.sh not work for centos 7/8

### ISSUE THREAD

**Issue by wecharyu** [apache/incubator-gluten#6437]
### Problem description

When trying to run setup-build-dependens.sh to prepare the build env, it reports errors:
```bash
++ yum -y install epel-release centos-release-scl
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container error was
14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
```

### System information

The repository issue in centos, and could not install cmake and gcc compiler for this info.

**Comment by zhztheplayer** [comment]
As a possible temporary solution, would you please try with [this method](https://github.com/apache/incubator-gluten/tree/main/tools/gluten-te/ubuntu/examples/buildhere-veloxbe-portable-libs) to create a build in docker container? It should be a more general way for building.

**Comment by wecharyu** [comment]
Thanks @zhztheplayer, our prod env is centos 7, I'm not sure if the lib built on ubuntu would work fine.

**Comment by zhztheplayer** [comment]
> Thanks @zhztheplayer, our prod env is centos 7, I'm not sure if the lib built on ubuntu would work fine.

I see. There might be a glibc compatibility issue since ubuntu 20.04 has higher version. I'll provide another option to build in centos 7 container (or lower) later.
