### ISSUE TITLE
[VL] deadlock during spill

### ISSUE THREAD

**Issue by FelixYBW** [apache/incubator-gluten#6477]
### Backend

VL (Velox)

### Bug description

several queries suffers from this bug. all task threads hangs during shuffle. The call stack:

org.apache.gluten.vectorized.ColumnarBatchOutIterator.nativeSpill(Native Method)
org.apache.gluten.vectorized.ColumnarBatchOutIterator.spill(ColumnarBatchOutIterator.java:80)
org.apache.gluten.vectorized.NativePlanEvaluator$1.spill(NativePlanEvaluator.java:87)
org.apache.gluten.memory.memtarget.Spillers$AppendableSpillerList.spill(Spillers.java:83)
org.apache.gluten.memory.memtarget.Spillers$WithMinSpillSize.spill(Spillers.java:66)
org.apache.gluten.memory.memtarget.TreeMemoryTargets.spillTree(TreeMemoryTargets.java:80)
org.apache.gluten.memory.memtarget.TreeMemoryTargets.spillTree(TreeMemoryTargets.java:55)
org.apache.gluten.memory.memtarget.TreeMemoryTargets.spillTree(TreeMemoryTargets.java:73)
org.apache.gluten.memory.memtarget.TreeMemoryTargets.spillTree(TreeMemoryTargets.java:55)
org.apache.gluten.memory.memtarget.TreeMemoryTargets.spillTree(TreeMemoryTargets.java:73)
org.apache.gluten.memory.memtarget.TreeMemoryTargets.spillTree(TreeMemoryTargets.java:55)
org.apache.gluten.memory.memtarget.spark.TreeMemoryConsumer.spill(TreeMemoryConsumer.java:115)
org.apache.spark.memory.TaskMemoryManager.acquireExecutionMemory(TaskMemoryManager.java:213) => holding Monitor(org.apache.spark.memory.TaskMemoryManager@1576620541})
org.apache.spark.memory.MemoryConsumer.acquireMemory(MemoryConsumer.java:136)
org.apache.gluten.memory.memtarget.spark.TreeMemoryConsumer.borrow(TreeMemoryConsumer.java:65)
org.apache.gluten.memory.memtarget.TreeMemoryTargets$Node.borrow0(TreeMemoryTargets.java:126)
org.apache.gluten.memory.memtarget.TreeMemoryTargets$Node.borrow(TreeMemoryTargets.java:118)
org.apache.gluten.memory.memtarget.TreeMemoryTargets$Node.borrow0(TreeMemoryTargets.java:126)
org.apache.gluten.memory.memtarget.TreeMemoryTargets$Node.borrow(TreeMemoryTargets.java:118)
org.apache.gluten.memory.memtarget.OverAcquire.borrow(OverAcquire.java:56)
org.apache.gluten.memory.memtarget.ThrowOnOomMemoryTarget.borrow(ThrowOnOomMemoryTarget.java:35)
org.apache.gluten.memory.listener.ManagedReservationListener.reserve(ManagedReservationListener.java:43) => holding Monitor(org.apache.gluten.memory.listener.ManagedReservationListener@223726602})
org.apache.gluten.vectorized.ColumnarBatchOutIterator.nativeHasNext(Native Method)
org.apache.gluten.vectorized.ColumnarBatchOutIterator.hasNextInternal(ColumnarBatchOutIterator.java:61)
org.apache.gluten.vectorized.GeneralOutIterator.hasNext(GeneralOutIterator.java:37)
scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:43)
org.apache.gluten.utils.iterator.IteratorsV1$InvocationFlowProtection.hasNext(IteratorsV1.scala:159)
org.apache.gluten.utils.iterator.IteratorsV1$IteratorCompleter.hasNext(IteratorsV1.scala:71)
org.apache.gluten.utils.iterator.IteratorsV1$PayloadCloser.hasNext(IteratorsV1.scala:37)
org.apache.gluten.utils.iterator.IteratorsV1$LifeTimeAccumulator.hasNext(IteratorsV1.scala:100)
org.apache.gluten.utils.iterator.IteratorsV1$ReadTimeAccumulator.hasNext(IteratorsV1.scala:127)
scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
scala.collection.convert.Wrappers$IteratorWrapper.hasNext(Wrappers.scala:31)
org.apache.gluten.vectorized.GeneralInIterator.hasNext(GeneralInIterator.java:31)
org.apache.gluten.vectorized.ColumnarBatchOutIterator.nativeHasNext(Native Method)
org.apache.gluten.vectorized.ColumnarBatchOutIterator.hasNextInternal(ColumnarBatchOutIterator.java:61)
org.apache.gluten.vectorized.GeneralOutIterator.hasNext(GeneralOutIterator.java:37)
scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:43)
org.apache.gluten.utils.iterator.IteratorsV1$ReadTimeAccumulator.hasNext(IteratorsV1.scala:127)
org.apache.gluten.utils.iterator.IteratorsV1$PayloadCloser.hasNext(IteratorsV1.scala:37)
org.apache.gluten.utils.iterator.IteratorsV1$IteratorCompleter.hasNext(IteratorsV1.scala:71)
scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
org.apache.spark.shuffle.ColumnarShuffleWriter.internalWrite(ColumnarShuffleWriter.scala:121)
org.apache.spark.shuffle.ColumnarShuffleWriter.write(ColumnarShuffleWriter.scala:231)
org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
org.apache.spark.scheduler.Task.run(Task.scala:131)
org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
org.apache.spark.executor.Executor$TaskRunner$$Lambda$648/859690736.apply(Unknown Source)
org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1471)
org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:750)

### Spark version

None

### Spark configurations

spark3.2

### System information

Velox System Info v0.0.2
Commit: 34dbec25d204fcb302893429350d37081feb5edf
CMake Version: 3.29.4
System: Linux-5.4.0-1063-aws
Arch: x86_64
CPU Name: Model name:                      Intel(R) Xeon(R) Platinum 8488C
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 9.4.0
C Compiler: /usr/bin/cc
C Compiler Version: 9.4.0
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

**Comment by marin-ma** [comment]
Seems like the deadlock is not from shuffle. The memory borrower is other op in the pipeline:
`org.apache.gluten.vectorized.ColumnarBatchOutIterator.nativeHasNext(Native Method)`

and the spiller is also other op in the pipeline:
`org.apache.gluten.vectorized.ColumnarBatchOutIterator.nativeSpill(Native Method)`

**Comment by FelixYBW** [comment]
@zhztheplayer Any insight? is there any issure/fix in Velox recently?

**Comment by zhztheplayer** [comment]
Didn't see this before. Is it possible to obtain C++ call stack?

**Comment by FelixYBW** [comment]
It's printed from Spark UI/Executor. How complex if we add the c++ stack to it?

**Comment by zhztheplayer** [comment]
> add the c++ stack to it

AFAIK it could be non-trivial work. Probably a manual way is to gdb attach to the hanging process.

**Comment by zhztheplayer** [comment]
Repeated with another workload. Hanging with call stack

```
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007f818600736e in folly::detail::(anonymous namespace)::nativeFutexWaitImpl (waitMask=4294967295, absSteadyTime=0x0, absSystemTime=0x0, expected=4294967293, addr=0x7f82d58dd098)
    at /opt/gluten/dev/vcpkg/.vcpkg/buildtrees/folly/src/4.05.20.00-935b4335b7.clean/folly/detail/Futex.cpp:126
#2  folly::detail::futexWaitImpl (futex=futex@entry=0x7f82d58dd098, expected=expected@entry=4294967293, absSystemTime=absSystemTime@entry=0x0, absSteadyTime=absSteadyTime@entry=0x0,
    waitMask=waitMask@entry=4294967295) at /opt/gluten/dev/vcpkg/.vcpkg/buildtrees/folly/src/4.05.20.00-935b4335b7.clean/folly/detail/Futex.cpp:254
#3  0x00007f818604e946 in folly::detail::futexWait<std::atomic<unsigned int> > (waitMask=4294967295, expected=4294967293, futex=0x7f82d58dd098)
    at /opt/gluten/dev/vcpkg/.vcpkg/buildtrees/folly/src/4.05.20.00-935b4335b7.clean/folly/detail/Futex-inl.h:94
#4  folly::detail::MemoryIdler::futexWait<std::atomic<unsigned int>, std::chrono::duration<long, std::ratio<1l, 1000000000l> > > (expected=4294967293, waitMask=4294967295, stackToRetain=1024,
    timeoutVariationFrac=0.5, idleTimeout=..., fut=std::atomic<unsigned int> = { 4294967293 })
    at /opt/gluten/dev/vcpkg/.vcpkg/buildtrees/folly/src/4.05.20.00-935b4335b7.clean/folly/detail/MemoryIdler.h:128
#5  folly::fibers::Baton::waitThread (this=0x7f82d58dd098) at /opt/gluten/dev/vcpkg/.vcpkg/buildtrees/folly/src/4.05.20.00-935b4335b7.clean/folly/fibers/Baton.cpp:70
#6  0x00007f818604ec10 in folly::fibers::Baton::wait<folly::fibers::Baton::wait()::<lambda()> > (mainContextFunc=..., this=0x7f82d58dd098)
    at /opt/gluten/dev/vcpkg/.vcpkg/buildtrees/folly/src/4.05.20.00-935b4335b7.clean/folly/fibers/Baton-inl.h:54
#7  folly::fibers::Baton::wait (this=this@entry=0x7f82d58dd098) at /opt/gluten/dev/vcpkg/.vcpkg/buildtrees/folly/src/4.05.20.00-935b4335b7.clean/folly/fibers/Baton.cpp:46
#8  0x00007f8182f6c39e in folly::futures::detail::waitImpl<folly::SemiFuture<folly::Unit>, folly::Unit> (f=...)
    at /opt/gluten/dev/vcpkg/vcpkg_installed/x64-linux-avx/include/folly/futures/Future-inl.h:2230
#9  0x00007f8182f6c890 in folly::SemiFuture<folly::Unit>::wait() & (this=0x7f82d58dd1c8) at /opt/gluten/dev/vcpkg/vcpkg_installed/x64-linux-avx/include/folly/futures/Future-inl.h:2337
#10 0x00007f8184cce4f8 in folly::SemiFuture<folly::Unit>::wait() && (this=0x7f82d58dd1c8) at /opt/gluten/dev/vcpkg/vcpkg_installed/x64-linux-avx/include/folly/futures/Future-inl.h:2343
#11 facebook::velox::exec::Task::MemoryReclaimer::reclaimTask (this=0x7f81d6b9af60, task=std::shared_ptr<facebook::velox::exec::Task> (use count 6, weak count 2) = {...}, targetBytes=45298480,
    maxWaitMs=0, stats=...) at /opt/gluten/ep/build-velox/build/velox_ep/velox/exec/Task.cpp:2828
#12 0x00007f8184cceb81 in facebook::velox::exec::Task::MemoryReclaimer::reclaim (this=0x7f81d6b9af60, pool=0x7f81d5460810, targetBytes=45298480, maxWaitMs=0, stats=...)
    at /opt/gluten/ep/build-velox/build/velox_ep/velox/exec/Task.cpp:2802
#13 0x00007f8185f4fe69 in facebook::velox::memory::MemoryReclaimer::reclaim (this=<optimized out>, pool=<optimized out>, targetBytes=<optimized out>, maxWaitMs=0, stats=...)
    at /opt/gluten/ep/build-velox/build/velox_ep/velox/common/memory/MemoryArbitrator.cpp:267
#14 0x00007f8182f91724 in gluten::ListenableArbitrator::shrinkCapacity (this=0x7f81d4c881c0, pools=..., targetBytes=45298480, allowSpill=<optimized out>, allowAbort=<optimized out>)
    at /opt/gluten/cpp/velox/memory/VeloxMemoryManager.cc:87
#15 0x00007f8182f73ac0 in gluten::WholeStageResultIterator::spillFixedSize (this=<optimized out>, size=<optimized out>) at /opt/gluten/cpp/velox/compute/WholeStageResultIterator.cc:258
#16 0x00007f82cebda3dd in gluten::ResultIterator::spillFixedSize (size=45298480, this=0x7f81d4db2780) at /opt/gluten/cpp/core/compute/ResultIterator.h:71
#17 Java_org_apache_gluten_vectorized_ColumnarBatchOutIterator_nativeSpill (env=0x7f81a058e260, wrapper=<optimized out>, iterHandle=622770257926, size=45298480)
    at /opt/gluten/cpp/core/jni/JniWrapper.cc:503
```

**Comment by zhztheplayer** [comment]
Probably related to https://github.com/facebookincubator/velox/pull/7761

**Comment by FelixYBW** [comment]
several queries hangs. looks a common issue

**Comment by FelixYBW** [comment]
for record, the callstack:

```
#0  0x00007fed2acd395d in syscall () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007fecbc2b955e in folly::detail::(anonymous namespace)::nativeFutexWaitImpl (waitMask=4294967295, absSteadyTime=0x0, absSystemTime=0x0, expected=4294967293, addr=0x7fecd45d2e68)
    at /home/binweiyang/gluten/dev/vcpkg/.vcpkg/buildtrees/folly/src/4.05.20.00-935b4335b7.clean/folly/detail/Futex.cpp:126
#2  folly::detail::futexWaitImpl (futex=futex@entry=0x7fecd45d2e68, expected=expected@entry=4294967293, absSystemTime=absSystemTime@entry=0x0, absSteadyTime=absSteadyTime@entry=0x0, waitMask=waitMask@entry=4294967295)
    at /home/binweiyang/gluten/dev/vcpkg/.vcpkg/buildtrees/folly/src/4.05.20.00-935b4335b7.clean/folly/detail/Futex.cpp:254
#3  0x00007fecbc3037b6 in folly::detail::futexWait<std::atomic<unsigned int> > (waitMask=4294967295, expected=4294967293, futex=0x7fecd45d2e68)
    at /home/binweiyang/gluten/dev/vcpkg/.vcpkg/buildtrees/folly/src/4.05.20.00-935b4335b7.clean/folly/detail/Futex-inl.h:94
#4  folly::detail::MemoryIdler::futexWait<std::atomic<unsigned int>, std::chrono::duration<long, std::ratio<1l, 1000000000l> > > (expected=4294967293, waitMask=4294967295, stackToRetain=1024, timeoutVariationFrac=0.5, idleTimeout=..., fut=...)
    at /home/binweiyang/gluten/dev/vcpkg/.vcpkg/buildtrees/folly/src/4.05.20.00-935b4335b7.clean/folly/detail/MemoryIdler.h:128
#5  folly::fibers::Baton::waitThread (this=this@entry=0x7fecd45d2e68) at /home/binweiyang/gluten/dev/vcpkg/.vcpkg/buildtrees/folly/src/4.05.20.00-935b4335b7.clean/folly/fibers/Baton.cpp:70
#6  0x00007fecbc303a80 in folly::fibers::Baton::wait<folly::fibers::Baton::wait()::<lambda()> > (mainContextFunc=..., this=0x7fecd45d2e68)
    at /home/binweiyang/gluten/dev/vcpkg/.vcpkg/buildtrees/folly/src/4.05.20.00-935b4335b7.clean/folly/fibers/Baton-inl.h:54
#7  folly::fibers::Baton::wait (this=this@entry=0x7fecd45d2e68) at /home/binweiyang/gluten/dev/vcpkg/.vcpkg/buildtrees/folly/src/4.05.20.00-935b4335b7.clean/folly/fibers/Baton.cpp:46
#8  0x00007fecb90024d1 in folly::futures::detail::waitImpl<folly::SemiFuture<folly::Unit>, folly::Unit> (f=...) at /home/binweiyang/gluten/dev/vcpkg/vcpkg_installed/x64-linux-avx/include/folly/futures/Future-inl.h:2230
#9  0x00007fecb90029f8 in folly::SemiFuture<folly::Unit>::wait() & (this=0x7fecd45d2fa8) at /home/binweiyang/gluten/dev/vcpkg/vcpkg_installed/x64-linux-avx/include/folly/futures/Future-inl.h:2337
#10 0x00007fecbaea6099 in folly::SemiFuture<folly::Unit>::wait() && (this=0x7fecd45d2fa8) at /home/binweiyang/gluten/dev/vcpkg/vcpkg_installed/x64-linux-avx/include/folly/futures/Future-inl.h:2343
#11 facebook::velox::exec::Task::MemoryReclaimer::reclaimTask (this=this@entry=0x7fecaab8ca60, task=..., targetBytes=targetBytes@entry=265080011, maxWaitMs=maxWaitMs@entry=0, stats=...)
    at /home/binweiyang/gluten/ep/build-velox/build/velox_ep/velox/exec/Task.cpp:2828
#12 0x00007fecbaea6771 in facebook::velox::exec::Task::MemoryReclaimer::reclaim (this=0x7fecaab8ca60, pool=<optimized out>, targetBytes=265080011, maxWaitMs=0, stats=...)
    at /home/binweiyang/gluten/ep/build-velox/build/velox_ep/velox/exec/Task.cpp:2802
#13 0x00007fecbc1fbc7a in facebook::velox::memory::MemoryReclaimer::reclaim (this=<optimized out>, pool=<optimized out>, targetBytes=<optimized out>, maxWaitMs=0, stats=...)
    at /home/binweiyang/gluten/ep/build-velox/build/velox_ep/velox/common/memory/MemoryArbitrator.cpp:267
#14 0x00007fecb902a672 in gluten::ListenableArbitrator::shrinkCapacity (this=0x7fecaab9f220, pools=..., targetBytes=265080011, allowSpill=<optimized out>, allowAbort=<optimized out>)
    at /home/binweiyang/gluten/cpp/velox/memory/VeloxMemoryManager.cc:87
#15 0x00007fecb900a5c6 in gluten::WholeStageResultIterator::spillFixedSize (this=<optimized out>, size=<optimized out>) at /home/binweiyang/gluten/cpp/velox/compute/WholeStageResultIterator.cc:258
#16 0x00007fecc2b5ee75 in gluten::ResultIterator::spillFixedSize (size=265080011, this=0x7fecd41759d0) at /home/binweiyang/gluten/cpp/core/compute/ResultIterator.h:71
#17 Java_org_apache_gluten_vectorized_ColumnarBatchOutIterator_nativeSpill (env=0x7feccb30da60, wrapper=<optimized out>, iterHandle=1013612281860, size=265080011) at /home/binweiyang/gluten/cpp/core/jni/JniWrapper.cc:503
```
