### ISSUE TITLE
[VL] Can not download special arrow gluten version: 15.0.0-gluten

### ISSUE THREAD

**Issue by baibaichen** [apache/incubator-gluten#6489]
### Problem description

https://github.com/apache/incubator-gluten/pull/5850 introduce special arrow gluten version: 15.0.0-gluten, we don't know where we can dowaload it from.

When we change API at gluten core, we can't easily to compile velox.

### System information

N/A

**Comment by dcoliversun** [comment]
Will get arrow:15.0.0-gluten by https://github.com/apache/incubator-gluten/blob/main/dev/builddeps-veloxbe.sh#L189-L199

**Comment by zhztheplayer** [comment]
Is the issue affecting CH backend's build?

I am opening a PR to remove the dependency from CH build https://github.com/apache/incubator-gluten/pull/6494

**Comment by baibaichen** [comment]
I am refactoring VL codes, see https://github.com/apache/incubator-gluten/pull/6403,  almost all codes are changed in velox side.

> Is the issue affecting CH backend's build?
> 
> I am opening a PR to remove the dependency from CH build #6494

**Comment by jinchengchenghh** [comment]
Fixed by https://github.com/apache/incubator-gluten/pull/6494
