### ISSUE TITLE
[VL] Build: --build_arrow=ON wipes --build_type=<TYPE> setting silently

### ISSUE THREAD

**Issue by zhztheplayer** [apache/incubator-gluten#6495]
The `source` code forces setting local var BUILD_TYPE to Release.

https://github.com/apache/incubator-gluten/blob/2e908c0868c05c55a3381c213fae0c415241b851/dev/builddeps-veloxbe.sh#L193

**Comment by zhztheplayer** [comment]
cc @PHILO-HE do we have to do `source` here? I think it's a command that we should carefully use than `bash`

**Comment by PHILO-HE** [comment]
> cc @PHILO-HE do we have to do `source` here? I think it's a command that we should carefully use than `bash`

@zhztheplayer, just aware of this issue. It's not necessary to use `source`. Let me fix that. Thanks!
