### ISSUE TITLE
Test code depends on benchmark code

### ISSUE THREAD

**Issue by xumingming** [apache/incubator-gluten#6553]
### Problem description

There are two separate switches which controls whether we build test and whether we build benchmarks:

```cmake
if(BUILD_TESTS)
  add_subdirectory(tests)
endif()

if(BUILD_BENCHMARKS)
  add_subdirectory(benchmarks)
endif()
```

But test code depends on benchmark lib unconditionally:

https://github.com/apache/incubator-gluten/blob/23af01dfaa5e72d72c4f5d4d0851a72ce9723013/cpp/velox/tests/CMakeLists.txt#L32

### System information

N/A

**Comment by FelixYBW** [comment]
closed by https://github.com/apache/incubator-gluten/pull/6563
