### ISSUE TITLE
[VL] Add an arch subdirectory for native libs package

### ISSUE THREAD

**Issue by wForget** [apache/incubator-gluten#6571]
### Description

There are machines with different CPU architectures in our internal hybrid cloud cluster, so I want to add an arch subdirectory for native libs package.

**Comment by zhztheplayer** [comment]
Do you mean to include libraries for different archs into the same bundled Gluten Jar?

**Comment by wForget** [comment]
> Do you mean to include libraries for different archs into the same bundled Gluten Jar?

Yeah, is this reasonable?

**Comment by zhztheplayer** [comment]
Sounds great to me. It's something missing from Gluten for long time.

**Comment by wForget** [comment]
> Sounds great to me. It's something missing from Gluten for long time.

Thank you, I will try to implement this.
