### ISSUE TITLE
[VL] Leverage Velox monolithic build for better caching to speed up CI

### ISSUE THREAD

**Issue by zhztheplayer** [apache/incubator-gluten#6577]
### Description

https://github.com/facebookincubator/velox/pull/9948 was merged. We'd change to the new build method to make Velox build up a single `libvelox.a` which can be easily cached among different CI runs as long as Velox's code doesn't get changed.

A possible issue is `libvelox.a` probably collides with Velox backend's `libvelox.so` more or less so we may consider changing name for the latter.

In most cases that Velox's code doesn't change, we expect the enhancement could save up to 1 hour during running CI, for a PR that changes Gluten's C++ code so requires to build C++ library on GitHub runner.

**Comment by PHILO-HE** [comment]
We have already enabled Velox's monolithic build. But I found when gluten test or benchmark is enabled, Gluten's build depends on some other lib files and some generated headers from Velox. So it is not enough to just cache libvelox.a, which makes this thing a bit complicated.

Currently, ccache is enabled in CI. We now just depend on ccache to speed up velox build. It's more stable and has better cache mechanism. It can also bring significant acceleration. Let's close this issue. Thanks!
