### ISSUE TITLE
[VL] Unexpected Branching in Physical Plan with Velox for Static/Dynamic Partition Writes

### ISSUE THREAD

**Issue by dcoliversun** [apache/incubator-gluten#6602]
### Backend

VL (Velox)

### Bug description

I find unexpected branching in physical plan with velox for static/dynamic partition writes.  

Original spark plan:
```plain
== Physical Plan ==
Execute InsertIntoHadoopFsRelationCommand (4)
+- WriteFiles (3)
   +- * Project (2)
      +- * Range (1)
```

Gluten spark plan:
```plain
== Physical Plan ==
Execute InsertIntoHadoopFsRelationCommand (12)
+- VeloxColumnarWriteFiles (11)
   :- ^ WriteFilesExecTransformer (6)
   :  +- ^ ProjectExecTransformer (5)
   :     +- ^ InputIteratorTransformer (4)
   :        +- RowToVeloxColumnar (2)
   :           +- * Range (1)
   +- RowToVeloxColumnar (10)
      +- WriteFiles (9)
         +- NoopLeaf (8)
```

And UI Gluten Tab shows that NoopLeaf/WriteFiles doesn't support by gluten.

Is this physical plan expected ?

### Spark version

Spark-3.5.x

**Comment by JkSelf** [comment]
@dcoliversun Yes. It is expected. And the detailed reason is [here](https://github.com/apache/incubator-gluten/blob/main/gluten-core/src/main/scala/org/apache/spark/sql/execution/ColumnarWriteFilesExec.scala#L238).
