### ISSUE TITLE
[VL] Can't build velox in Debug mode with builddeps-veloxbe.sh.

### ISSUE THREAD

**Issue by JaeeunKimMX** [apache/incubator-gluten#6638]
### Problem description

In short, with `BUILD_ARROW=ON` (this is the default), the `BUILD_TYPE` is ignored.

I tried to build Velox in Debug with Gluten using `builddeps-veloxbe.sh`. If I understand the scripts correctly, with `./dev/builddeps-veloxbe.sh --build_type=Debug`, I can propagate down the build type option to Velox. However, the build output, `libvelox.so` had no debug information.

Digging into it a little bit, I've found out that the `BUILD_TYPE` variable is overwritten while building Arrow in `bulild_arrow.sh` as "Release" in the `builddeps-veloxbe.sh` so that the `BUILD_TYPE` is not properly propagated. 
```
function build_arrow {
  echo "Start to build Arrow"
  export SUDO=sudo
  cd $GLUTEN_DIR/dev
  source build_arrow.sh                  // This overwrites "BUILD_TYPE" as Release.
  prepare_arrow_build
  build_arrow_cpp
  echo "Finished building arrow CPP"
  build_arrow_java
  echo "Finished building arrow Java"
}
```

I modified the scripts a little bit and succeeded in building, anyway. Thank you.
on tag: v1.2.0-rc0
 

### System information

Velox System Info v0.0.2
Commit: c21503548416a596c5403cfbfbd20c4bc8bc5e47
CMake Version: 3.28.3
System: Linux-6.5.0-41-generic
Arch: x86_64
CPU Name: Model name:                         Intel(R) Core(TM) i7-14700K
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 11.4.0
C Compiler: /usr/bin/cc
C Compiler Version: 11.4.0
CMake Prefix Path: /usr/local;/usr;/;/usr/local/lib/python3.10/dist-packages/cmake/data;/usr/local;/usr/X11R6;/usr/pkg;/opt

**Comment by PHILO-HE** [comment]
@JaeeunKimMX, thanks for reporting this issue. We should have fixed this issue in v1.2.0-rc1. The corresponding pr is https://github.com/apache/incubator-gluten/pull/6500. If the issue still exists, please let us know.

**Comment by JaeeunKimMX** [comment]
@PHILO-HE Oh, it's been fixed already. It would be that there was no v1.2.0-rc1 when I got it :).  I've tested it with the tag and it works! Thank you for your reply.

**Comment by PHILO-HE** [comment]
> @PHILO-HE Oh, it's been fixed already. It would be that there was no v1.2.0-rc1 when I got it :). I've tested it with the tag and it works! Thank you for your reply.

You're welcome! I'm closing this issue.
