### ISSUE TITLE
[VL] Support pushdown Timestamp type to scan

### ISSUE THREAD

**Issue by WangGuangxin** [apache/incubator-gluten#6642]
### Description

Velox should already support pushdown timestamp type to scan now.

**Comment by FelixYBW** [comment]
> ### Description
> Velox should already support pushdown timestamp type to scan now.

Do you mean timestamp support of table scan or filter in Scan?

Timestamp in table scan is not yet fully supported. PRs are ready but not merged

**Comment by rui-mo** [comment]
Pushdown of timestamp filter has been supported in Velox, and it works for the INT96 timestamp reader.

**Comment by jinchengchenghh** [comment]
You could reopen it if you still have problem.
