### ISSUE TITLE
[CORE] ParquetFileForamt/OrcFileFormat has code like `if (xxx && false)`

### ISSUE THREAD

**Issue by PHILO-HE** [apache/incubator-gluten#6649]
### Description

Not sure why we make this if branch always skipped.

See https://github.com/apache/incubator-gluten/blob/main/shims/spark32/src/main/scala/org/apache/spark/sql/execution/datasources/parquet/ParquetFileFormat.scala#L204

**Comment by PHILO-HE** [comment]
Hi @binmahone, do you remember the reason?

**Comment by gaoyangxiaozhu** [comment]
@PHILO-HE does you try if CI pass if remove the false check ?

**Comment by PHILO-HE** [comment]
> @PHILO-HE does you try if CI pass if remove the false check ?

@gaoyangxiaozhu, thanks for your comment! I will try to do that.

**Comment by binmahone** [comment]
> Hi @binmahone, do you remember the reason?

Sorry I can't really recall. When the intial PR was checked in, velox backend did not actually supported native writer.

**Comment by PHILO-HE** [comment]
> > Hi @binmahone, do you remember the reason?
> 
> Sorry I can't really recall. When the intial PR was checked in, velox backend did not actually supported native writer.

@binmahone, I see. Anyway, thanks for your reply!

**Comment by PHILO-HE** [comment]
As confirmed with @JkSelf, we can remove this code to always use vanilla Spark's API for Velox backend. #6663 is removing the useless code.
