### ISSUE TITLE
[VL] Add config can disable rewrite collect in objectHashAggregate

### ISSUE THREAD

**Issue by zml1206** [apache/incubator-gluten#6688]
### Description

Spark collect is `TypedImperativeAggregate` which can use objectHashAggregate, but velox collect is `DeclarativeAggregate`. `CollectRewriteRule` is a logical plan rule, it will replace spark collect to velox collect. If a collect aggregate is `ObjectHashAggregate` in vanilla spark, it will change to `SortAggregate` in gluten. The performance of `ObjectHashAggregate` is much greater than `SortAggregate`, if fallback it will cause performance regression.
Add config `spark.gluten.sql.columnar.backend.velox.objectHashAggregate.collect.rewrite.enabled`, it can disable rewrite collect in objectHashAggregate.

**Comment by zml1206** [comment]
cc @zhztheplayer what do you think?

**Comment by zhztheplayer** [comment]
+1 Let's add the option. Thanks.

**Comment by FelixYBW** [comment]
If we need the option to be set true always, let's remove the option and just implement as it's true. We can document it in code or in the PR

**Comment by zml1206** [comment]
> If we need the option to be set true always, let's remove the option and just implement as it's true. We can document it in code or in the PR

Add this option is to allow users to selectively disable when regression occurs.

**Comment by FelixYBW** [comment]
> 
> Add this option is to allow users to selectively disable when regression occurs.

Did you see regression in some cases?

**Comment by zml1206** [comment]
> Did you see regression in some cases?

Yes, vanilla spark is ObjectHashAggregate, gluten fallback to SortAggregate.

**Comment by PHILO-HE** [comment]
@zml1206, I remember Gluten replaces ObjectHashAggregate with its HashAggregate, not SortAggregate. Right?

**Comment by zml1206** [comment]
> @zml1206, I remember Gluten replaces ObjectHashAggregate with its HashAggregate, not SortAggregate. Right?

Yea, but `CollectRewriteRule` rewrite collect to velox_collect, velox_collect is not `TypedImperativeAggregate`.
It affects the aggregate type selection when converting spark logical plan to physical plan, only  `TypedImperativeAggregate` can create `ObjectHashAggregateExec`. For example, `select collect_set(string_field), velox_unsupport_udaf() from t`, in vanilla spark is `ObjectHashAggregateExec`, in gluten is `SortAggregateExec`.

**Comment by zhztheplayer** [comment]
> If we need the option to be set true always, let's remove the option and just implement as it's true. We can document it in code or in the PR

It's feasible to develop a mechanism to disable ops or expressions by two single options, for example:

```
set <prefix>.disabledOps=HashAggregateExec,ShuffleExchangeExec,...
set <prefix>.disabledExpressions=concat,collect_list,...
```

So we don't have to maintain so many options to control fallback configurations.

cc @PHILO-HE I see we already have config option `spark.gluten.expression.blacklist`, is that one doing the same things as I mentioned?

**Comment by PHILO-HE** [comment]
> cc @PHILO-HE I see we already have config option spark.gluten.expression.blacklist, is that one doing the same things as I mentioned?

Yes, this existing config can be used to disable certain expressions.
