### ISSUE TITLE
how to add libhdfs conf when running spark-sql

### ISSUE THREAD

**Issue by lihao712** [apache/incubator-gluten#6728]
### Backend

VL (Velox)

### Bug description

when I what to running spark sql with gluten with hdfs support, I add spark.executorEnv.LIBHDFS3_CONF="/path/to/hdfs-client.xml in spark.defaults.conf, but this path in running sql can't be read by executor, but --files way can't be used in spark-sql query, so what should I do? maybe add this hdfs-client.xml to all clister node path? it's too expensive and unusable,should someway can help me sovle this problem?

### Spark version

None

**Comment by ArnavBalyan** [comment]
Hi @lihao712, you can place the file on HDFS, and providing the HDFS path should work.
`"spark.executorEnv.LIBHDFS3_CONF": "<HDFS Path to XML>"`
cc @FelixYBW for confirmation thanks!

**Comment by PHILO-HE** [comment]
@ArnavBalyan is right.

@lihao712, please refer to this document:
https://github.com/apache/incubator-gluten/blob/main/docs/get-started/Velox.md#configuration-about-hdfs-support

**Comment by jinchengchenghh** [comment]
You could also follow this document, https://github.com/apache/incubator-gluten/blob/main/docs/get-started/Velox.md
Build velox with the compile option ENABLE_HDFS=ON
