### ISSUE TITLE
branch-1.2's process_setup_alinux3(get_velox.sh) is out of date

### ISSUE THREAD

**Issue by xumingming** [apache/incubator-gluten#6735]
### Problem description

It reference a directory: `third_party` which is already removed in Velox:

```
function process_setup_alinux3 {
 ....
  sed -i "s/\${CMAKE_INSTALL_LIBDIR}/lib64/" third_party/CMakeLists.txt
}
```

### System information

N/A

### CMake log

```bash
N/A
```

**Comment by PHILO-HE** [comment]
@xumingming, could you propose a fix to branch-1.2? cc @weiting-chen

**Comment by PHILO-HE** [comment]
Just noted it is removed from main branch by this pr: https://github.com/apache/incubator-gluten/pull/6363. @weiting-chen, could you help port the patch to branch-1.2?

**Comment by PHILO-HE** [comment]
@xumingming, this issue has been fixed by https://github.com/apache/incubator-gluten/pull/6773/. Thanks for reporting this issue! I'm closing it.
