### ISSUE TITLE
[CORE] Fragile in-AQE check in columnar rule appliers

### ISSUE THREAD

**Issue by zhztheplayer** [apache/incubator-gluten#6748]
Columnar rule appliers adopts `AdaptiveContext` which relies on an empirical value (introduced in https://github.com/apache/incubator-gluten/pull/1127) to look up on the current stack trace to determine whether it's in AQE planning ([example](https://github.com/apache/incubator-gluten/blob/531e82a5bb7c93603661f4e0c5d98317d58cf109/gluten-core/src/main/scala/org/apache/gluten/extension/columnar/heuristic/HeuristicApplier.scala#L43-L48)). This method is fragile given that different Spark version (including user-customized versions) may have different AQE call stacks.

We'd make the code more robust perhaps by doing a search on stack frames rather than using a empirical magic number. And eventually we should remove this in-AQE check since this is basically caller-sensitive code which impacts portability and encapsulation.

**Comment by PHILO-HE** [comment]
> We'd make the code more robust perhaps by doing a search on stack frames.

@zhztheplayer, yes, it's better to do this. 

Not sure we still depend on this adaptive context check now.
