### ISSUE TITLE
[VL] Missing Spill (Memory) and Spill (Disk) metrics

### ISSUE THREAD

**Issue by marin-ma** [apache/incubator-gluten#6763]
### Backend

VL (Velox)

### Bug description

When spill is triggered, the spilled size is not reported to spark task metrics.

### Spark version

None

**Comment by marin-ma** [comment]
Shuffle spill is added in https://github.com/apache/incubator-gluten/pull/6740
Spill from velox pipeline is still missing hence the reported spill size can be smaller than the actual spill size.

**Comment by FelixYBW** [comment]
What's the spill reported from velox? memory spill or disk spill?

**Comment by marin-ma** [comment]
> What's the spill reported from velox? memory spill or disk spill?

@FelixYBW Spill(Memory) is the in-memory raw data to be spilled, usually uncompressed. Spill(Disk) is the actual bytes spilled to disks, equals to the spill file size. 
For velox pipeline, we may count Spill(Memory) from the memory allocation: before spill - after spill allocated memory size, and minus the shrunk bytes. And count Spill(Disk) from the spill file size.

**Comment by FelixYBW** [comment]
What's the current spill size reported from Velox?

**Comment by jinchengchenghh** [comment]
I have supported the metric in spill, can we get it on the UI? https://github.com/facebookincubator/velox/pull/6076/files
