### ISSUE TITLE
Nan isn't supported in Velox backend

### ISSUE THREAD

**Issue by FelixYBW** [apache/incubator-gluten#683]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Some UTs are skipped since Nan isn't supported in Velox. Currently Velox return as null.

**Describe the solution you'd like**
Add Nan support to Velox, align with Spark's results

Record here

@jinchengchenghh

**Comment by acvictor** [comment]
@FelixYBW can you please share the PR where NAN support was added?
