### ISSUE TITLE
[VL] Driver memory leak with soft affinity duplicate reading

### ISSUE THREAD

**Issue by jackylee-ch** [apache/incubator-gluten#6995]
### Backend

VL (Velox)

### Bug description

Currently, we monitor TaskEnd/StageEnd events to update and clean up FilePartition and Executor data for duplicate reading. However, in actual execution, we found that the current monitoring logic is slow, and it would cause spark event accumulation. When the events eventually exceed the capacity defined by Spark and they will be discarded. As a result, a large amount of information remains in rddPartitionInfoMap and stageInfoMap and cannot be discarded, which leads to frequent FGC in driver and finnaly OOM.

Bellow is the log for Event discard.
![image](https://github.com/user-attachments/assets/09fed7b4-9af4-4d19-93db-3e9de8c4c879)

Bellow is the memory analyze for our online driver. The driver memory is 2.2G and the memory used by SoftAffinityManager is 1.5G.
<img width="687" alt="image" src="https://github.com/user-attachments/assets/a1f364d7-e49a-4802-a83b-840f650879b8">

### Spark version

Spark-3.5.x

**Comment by jackylee-ch** [comment]
@zhli1142015 We may need to refact the code for duplicate reading or close the duplicated reading by default.

**Comment by zhli1142015** [comment]
Thanks for reporting this, may I ask some questions about this?

> Currently, we monitor TaskEnd/StageEnd events to update and clean up FilePartition and Executor data for duplicate reading.

Does this mean you use partial logic for SA duplicate reading detection? Or you don't use SA at all, SA just impacts you.

> When the events eventually exceed the capacity defined by Spark and they will be discarded.

Yes, if some key events(SparkListenerStageCompleted) are discarded, the middle states would not be cleared, this should be a bug. I can take a look.

> @zhli1142015 We may need to refact the code for duplicate reading or close the duplicated reading by default.

Here is the config to disable the duplicate reading: spark.gluten.soft-affinity.duplicateReadingDetect.enabled

**Comment by jackylee-ch** [comment]
> Does this mean you use partial logic for SA duplicate reading detection? Or you don't use SA at all, SA just impacts you.

We are using velox cache and SA in our environment and found driver memory OOM recentlly. After analyze the heap.dump, we found the `SA duplicate reading detection` is the reason that memory is raising continually.

> Yes, if some key events(SparkListenerStageCompleted) are discarded, the middle states would not be cleared, this should be a bug. I can take a look.

Great, thanks.

> Here is the config to disable the duplicate reading: spark.gluten.soft-affinity.duplicateReadingDetect.enabled

Yeap, we have already use it.
