### ISSUE TITLE
[CH] Different result from `get_json_object`

### ISSUE THREAD

**Issue by lgbo-ustc** [apache/incubator-gluten#7014]
### Backend

CH (ClickHouse)

### Bug description

[Expected behavior] and [actual behavior].

```sql
select get_json_object('{"a":"\\\"b", "x":"u0001}Uûu0010Jw\\\"<洫C"}\\0', '$.a');
```
gluten returns `NULL`, vanilla returns `"b`

```sql
select get_json_object('{"a":"232\\b123", "x":"xdd"}', '$.a')
```
gluten returns `23123`, vanilla returns `232123`

```sql
get_json_object('{"a":"\\\"b", "x":"1232\01232"}', '$.x')
```
gluten returns `123232`, vanilla returns `1232 32`

### Spark version

None

**Comment by lgbo-ustc** [comment]
There have been a bundle of PRs to fix the difference. 
https://github.com/apache/incubator-gluten/issues/3750
https://github.com/apache/incubator-gluten/issues/3337
https://github.com/apache/incubator-gluten/issues/5303

**Comment by zhanglistar** [comment]
Version problem?

**Comment by lgbo-ustc** [comment]
a new corner case
