### ISSUE TITLE
[CH] Eliminate duplicate calculations using common subexpressions

### ISSUE THREAD

**Issue by lgbo-ustc** [apache/incubator-gluten#7054]
### Description

Solve one problem of #7051

**Comment by taiyang-li** [comment]
sql: 
```
select coalesce(day,"all") as daytime,
coalesce(type,"all") as type,
coalesce(value_money,"all") as value_vmoney ,
sum(case when type in (1,2) and  action=8 then value_vmoney else 0 end)/60 as total_value_vmoney
from
(select day,type,
nvl(cast(value_vmoney as bigint),0) as value_money,
action,
type,
cast(value_vmoney as bigint) as value_vmoney
from
(
select day,event.event_info["type"] as type,
event.event_info["action"] as action,
event.event_info["value_vmoney"] as value_vmoney
from bigolive.bigo_show_user_event_hour_orc a
where day='2024-08-27' and event_id ='011441004'
and event.event_info["type"] in (1,2,4)
) a
) b
group by day,type,value_money
```

**Comment by taiyang-li** [comment]
Cause: Before CSE optimization, there were two duplicate Alias expressions in the Project operator, both of which were 'event#33.event_info[type] AS type#0'.  After the CSE Rule detects that it is a duplicate expression, it adds a pre-project operator for current project operator. The pre-project operation contains `event#33.event_info[type] AS type#0 AS event#33.event_info[type] AS type#0#83`, which is an Alias expression upon another Alias expression, and of course doesn't make sense.
