### ISSUE TITLE
[VL] Output metrics are counted multiple times for InputIterator of broadcasted exchange

### ISSUE THREAD

**Issue by ivoson** [apache/incubator-gluten#7079]
### Backend

VL (Velox)

### Bug description

Below screenshot shows the metrics from tpcds q6. We can see that the output rows was counted multiple times(same as the task number of the join stage). From task execution's perspective, the task indeed read the data multiple times. While from a sql plan node's perspective, this is confusing since the output row counts of the plan node is not right.

I am wondering that does this make sense and shall we count only once for inputIterator of broadcasted exchange.

![image](https://github.com/user-attachments/assets/5f557af5-7439-486e-b54c-69966c061043)

### Spark version

None

**Comment by zhztheplayer** [comment]
@ivoson Would you like to help check how vanilla Spark handles this case? Thanks.

**Comment by ivoson** [comment]
> @ivoson Would you like to help check how vanilla Spark handles this case? Thanks.

Sure, checking on this.

**Comment by ivoson** [comment]
cc @ulysses-you I am wondering do you have any thoughts about this? Thanks.

**Comment by ulysses-you** [comment]
For now the output row number is `broadcasted rows * numPartitions`. I agree it may make user who know Spark a lot a bit confused. I'm fine to use the original broadcasted rows if there is a easy way to resolve it.

**Comment by ivoson** [comment]
> For now the output row number is `broadcasted rows * numPartitions`. I agree it may make user who know Spark a lot a bit confused. I'm fine to use the original broadcasted rows if there is a easy way to resolve it.

I am thinking that maybe we can only collect the metrics from one of the tasks(task 0) for a wrapper of broadcast exchange which is easy to implement but a little bit tricky...
Do you think the proposal make sense? cc @zhztheplayer @ulysses-you 
If it sounds good to you, I'll create a PR for this.

**Comment by FelixYBW** [comment]
Vanilla spark create the hashtable on driver and broadcast to worker. It's one optimization pending in Velox.

I agree your proposal.

**Comment by Surbhi-Vijay** [comment]
Duplicate issue: [[VL] Incorrect Metrics in InputIteratorTransformer](https://github.com/apache/incubator-gluten/issues/4672)

**Comment by FelixYBW** [comment]
> Duplicate issue: [[VL] Incorrect Metrics in InputIteratorTransformer](https://github.com/apache/incubator-gluten/issues/4672)

Can you verify PR #7167?

**Comment by Surbhi-Vijay** [comment]
We validated it internally and post this patch metrics are correctly reported for broadcast exchange.
