### ISSUE TITLE
[CH] Performance regression when reading files from Hive(HDFS)

### ISSUE THREAD

**Issue by zhanglistar** [apache/incubator-gluten#7177]
### Backend

CH (ClickHouse)

### Bug description
SQL: `select count(distinct country) from ttt where day = '2024-08-26' and hour = '00'`

Related PR: https://github.com/apache/incubator-gluten/pull/6841

371be6f860c2b409ea70a79e0c2e4e72a2624e38 ok
<img width="1388" alt="image" src="https://github.com/user-attachments/assets/0a2dc212-ce9e-4afc-afac-24549297c5ab">
<img width="548" alt="image" src="https://github.com/user-attachments/assets/1028f1f7-bd02-4fc5-8704-b5366f18e4a7">

371d448c3b512b1cbb3272e932cb7a57b9da4ba6 NOT OK
<img width="1384" alt="image" src="https://github.com/user-attachments/assets/81065ac9-92f7-4581-be74-c4949831f54a">
<img width="483" alt="image" src="https://github.com/user-attachments/assets/302d5498-d7ad-46aa-943c-0eefd0b1e793">

vanila:
<img width="1390" alt="image" src="https://github.com/user-attachments/assets/1b918ccb-b487-4ec0-9e0b-b75c35f70e47">

About 4.6x slower than vanila 332, and 18x slower than last commit.

### Spark version

Spark-3.3.x

**Comment by loneylee** [comment]
Thanks for finding the problem, I will fix it as soon as possible.
