### ISSUE TITLE
[VL] Aggregate window gets the wrong result in 1.2.0

### ISSUE THREAD

**Issue by ccat3z** [apache/incubator-gluten#7194]
### Backend

VL (Velox)

### Bug description

Aggregate window gets the wrong result

``` scala
-- Data
(for { x <- 1 to 4500 } yield { (x,1) }).toDF("id", "order_num")
     
-- Query
SELECT
  id,
  SUM(num) OVER(ORDER BY num DESC) AS sum
FROM test
```

Expect: `sum: 4500`

Actual: `sum: 4096 ... 4500`

### Spark version

None

**Comment by ccat3z** [comment]
cc @kecookier

**Comment by ccat3z** [comment]
This issue can be solved by disabling RowsStreamingWindowBuild. I guess that RowsStreamingWindowBuild might not be compatible with some aggregate case. I tried copying the logic of 'supportRowsStreaming()' from the update branch, but it didn't work. cc @JkSelf

**Comment by JkSelf** [comment]
@ccat3z I will look at this issue later. Thanks.

**Comment by JkSelf** [comment]
@ccat3z Can you help to verify https://github.com/facebookincubator/velox/pull/10979 in your env? Thanks.

**Comment by ccat3z** [comment]
> @ccat3z Can you help to verify [facebookincubator/velox#10979](https://github.com/facebookincubator/velox/pull/10979) in your env? Thanks.

It works. Thanks.

**Comment by JkSelf** [comment]
Fixed in https://github.com/facebookincubator/velox/pull/10979.
