### ISSUE TITLE
[CORE] Make push down filter to scan as a individual rule

### ISSUE THREAD

**Issue by zml1206** [apache/incubator-gluten#7203]
### Description

Currently, we push down filter to scan in OffloadFilter. We can create a new rule after offload to process it to avoid overly complex offload and facilitate maintenance.
In addition, push down filter to scan seems to only bring benefits, so it should be pushed down as much as possible, so after adding this rule, it seems that PushFilterToScan and RemoveFilter can be removed from RAS rule.

**Comment by zml1206** [comment]
If both filter and scan are offloaded, filter condition can be pushed down to scan. This must be true? @zhztheplayer

**Comment by zhouyuan** [comment]
CC @rui-mo
