### ISSUE TITLE
Using the static glog library will cause the loading of libvelox.so to fail

### ISSUE THREAD

**Issue by JinHelin404** [apache/incubator-gluten#7208]
### Backend

VL (Velox)

### Bug description

Using the local static glog library to compile velox and gluten will result in the following error:

> INFO JniLibLoader: Trying to load library libvelox.so
> ERROR: something wrong with flag 'timestamp_in_logfile_name' in file '/gluten/ep/build-velox/velox-cicd/thirdparty/src/glog-0.6.0/src/logging.cc'.  One possibility: file '/gluten/ep/build-velox/velox-cicd/thirdparty/src/glog-0.6.0/src/logging.cc' is being linked both statically and dynamically into this executable.

### Spark version

Spark-3.2.x

**Comment by zhztheplayer** [comment]
As this doesn't likely happen on all platforms. Can you attach your system information? Thanks.

**Comment by JinHelin404** [comment]
> Why this doesn't happen in CI? Any preconditions to repeat the issue?

@zhztheplayer This will happen when we compile velox and gluten with static glog lib and without ENABLE_GLUTEN_VCPKG=ON:

https://github.com/apache/incubator-gluten/blob/main/cpp/core/CMakeLists.txt#L216.
