### ISSUE TITLE
[CH] Diff of grouping sets query

### ISSUE THREAD

**Issue by KevinyhZou** [apache/incubator-gluten#7220]
### Backend

CH (ClickHouse)

### Bug description

do the query
```
select '2024-08-26' as day, id,name from
(
select
id, name
from test_tbl2
group by id, name
grouping sets((id),(id,name))
) where name  = 'a124'
;

```

the valina result is 
![image](https://github.com/user-attachments/assets/edbd767a-94d3-46fc-ab92-10dc69c746d6)

the gluten result is empty.

### Spark version

Spark-3.3.x

**Comment by KevinyhZou** [comment]
![image](https://github.com/user-attachments/assets/001e2e7e-5967-48d9-9f68-305e31687f6e)

**Comment by KevinyhZou** [comment]
```
CHNativeColumnarToRow
+- ^(2) ProjectExecTransformer [2024-08-26 AS day#0, id#12L, name#13]
   +- ^(2) HashAggregateTransformer(keys=[id#12L, name#13, spark_grouping_id#11L], functions=[], isStreamingAgg=false)
      +- ^(2) InputIteratorTransformer[id#12L, name#13, spark_grouping_id#11L]
         +- ColumnarExchange hashpartitioning(id#12L, name#13, spark_grouping_id#11L, 1), ENSURE_REQUIREMENTS, [plan_id=112], [shuffle_writer_type=hash], [OUTPUT] List(id:LongType, name:StringType, spark_grouping_id:LongType)
            +- ^(1) HashAggregateTransformer(keys=[id#12L, name#13, spark_grouping_id#11L], functions=[], isStreamingAgg=false)
               +- ^(1) FilterExecTransformer (isnotnull(name#13) AND (name#13 = a124))
                  +- ^(1) ExpandExecTransformer [[id#6L, null, 1], [id#6L, name#7, 0]], [id#12L, name#13, spark_grouping_id#11L]
                     +- ^(1) ProjectExecTransformer [id#6L, name#7]
                        +- ^(1) NativeFileScan parquet default.test_tbl2[id#6L,name#7,day#8] Batched: true, DataFilters: [], Format: Parquet, Location: CatalogFileIndex(1 paths)[hdfs://testcluster/user/hive/warehouse/test_tbl2], PartitionFilters: [], PushedFilters: [], ReadSchema: struct<id:bigint,name:string>

```

分别需要针对[id#6L, null, 1], [id#6L, name#7, 0]], [id#12L, name#13, spark_grouping_id#11L] 三组fields 进行expand，按照`ExpandTransform` 逻辑，首先对[id#6L, null, 1]执行expand，数据到下游后，被filter `where name = 'a124'`， 无行数输出，导致ISource中误认为数据已经结束
![image](https://github.com/user-attachments/assets/67bb722b-dfba-497a-a9b8-daa4b9836ab6)

从而导致提前结束expand，其他两组fields 的expand 未执行，从而导致无结果输出。

**Comment by lgbo-ustc** [comment]
奇怪，filter过滤后block为空，按理不应该会往下游传递一个空的block的

**Comment by KevinyhZou** [comment]
output port 被设置为finished了 ，导致expandTransform 这里
![image](https://github.com/user-attachments/assets/d1d2cf39-7e9f-4417-b6b4-7c7248ccc5a0)

input 也被close掉了

**Comment by lgbo-ustc** [comment]
不明白。 filter 对一个block过滤后，结果是空的，这个应该是常见的情况。这也不会造成它会给下游算子一个空的block

**Comment by lgbo-ustc** [comment]
The filter transform enter into, it seems unreasonable
![image](https://github.com/user-attachments/assets/2d41e530-df4b-4189-aaa5-65a9879b4cce)

**Comment by lgbo-ustc** [comment]
Should materialize the constnull column

**Comment by lgbo-ustc** [comment]
正常情况下，如果某一列是const，则会认为起后续block的对应列也都是const的。但在expand算子，这个默认被打破了。出现部分block的该位置列是const，其他的确不是。应该消除该列为const的情况。
