### ISSUE TITLE
[VL] row2VeloxColumnar bad performance

### ISSUE THREAD

**Issue by FelixYBW** [apache/incubator-gluten#7223]
### Description

The query has hive table scan which output complex datatype. Gluten elapsed time is >2x worse than Vanilla Spark. 93% percent of time is spending on RowToVeloxColumnar

**Comment by FelixYBW** [comment]
postpone the r2c until complex type is not presented

**Comment by zml1206** [comment]
It seems that not only complex types, too many rows will also be slow.
