### ISSUE TITLE
[VL] #6942 breaks shared lib loader 

### ISSUE THREAD

**Issue by Yohahaha** [apache/incubator-gluten#7241]
### Problem description

#6942 use `System.mapLibraryName(libName)` to get lib name, which will convert `libboost_atomic.so.1.84.0` to `libboost_atomic.so.1.84.0.so`, it's wrong.

![image](https://github.com/user-attachments/assets/765b0dfc-592c-43fd-bcfc-c8be414dbffe)

### System information

n/a

**Comment by Yohahaha** [comment]
```
Caused by: java.io.FileNotFoundException: liblibboost_atomic.so.1.84.0.so
	at org.apache.gluten.jni.JniLibLoader.moveToWorkDir(JniLibLoader.java:206)
	at org.apache.gluten.jni.JniLibLoader.loadAndCreateLink(JniLibLoader.java:184)
	... 42 more
```

**Comment by Yohahaha** [comment]
@PHILO-HE @zhouyuan could we keep one CI for dynamic lib packing ?

**Comment by zhztheplayer** [comment]
Would someone like to fix this first ? Seems to be a minor one. cc @wForget

**Comment by Yohahaha** [comment]
> Would someone like to fix this first ? Seems to be a minor one. cc @wForget

I will fix this issue later.

**Comment by wForget** [comment]
> https://github.com/apache/incubator-gluten/pull/6942 use System.mapLibraryName(libName) to get lib name

Is this the root cause? The previous behavior also seemed to use `System.mapLibraryName`

https://github.com/apache/incubator-gluten/blob/3af5bac7660d97d5438950bd49aaafbcdc51d70e/gluten-substrait/src/main/java/org/apache/gluten/vectorized/JniLibLoader.java#L195

**Comment by wForget** [comment]
Introduced in #6791?

**Comment by wForget** [comment]
`System.mapLibraryName` does result in an incorrect libname, we can remove it in `SharedLibraryLoader`

![image](https://github.com/user-attachments/assets/6e1663fd-4527-4ef5-b757-fcc2a00a30ed)

**Comment by wForget** [comment]
> @PHILO-HE @zhouyuan could we keep one CI for dynamic lib packing ?

How about adding a `run TPC-H / TPC-DS` step to `velox_weekly.yml`?

**Comment by zhouyuan** [comment]
@Yohahaha @wForget 
This is the annoying issue I mentioned to you before, we need to carefully maintain those codes, with different platforms.
Yes, the CentOS 8 based tests is still using dynamic packaging method, the gap is there's not TPCH/DS test on it. Using gluten-it should be able to add the tests quickly.  Let me try to add one for this

thanks, -yuan
