### ISSUE TITLE
[VL] offload table scan when filter need fallback

### ISSUE THREAD

**Issue by FelixYBW** [apache/incubator-gluten#7261]
### Description

currently when a filter has UDF and fallback, the table scan is also fallback. We should offload table scan since it can benefit from native and much more expensive than filter and new C2R.

In this query, parquet scan output int and string only.

![image](https://github.com/user-attachments/assets/3b5d5263-2ebf-4b11-bdb3-2d3d76d10cd4)

**Comment by zhztheplayer** [comment]
There is a pending PR possibly related to this topic https://github.com/apache/incubator-gluten/pull/7215

@zml1206 Would we still be able to optimize against such issues after that PR get landed?

**Comment by FelixYBW** [comment]
Should be. Let me do a quick test once @zml1206 resolve conflicts

**Comment by zml1206** [comment]
Conflicts resolved. But I'm sorry I don't understand why scan will fallback. Is it because RAS is enabled?

**Comment by zml1206** [comment]
Can we determine whether expression supports offload? @zhztheplayer There are three layers of filters here. The first layer is pushedDownFilters of FileSourceScanExec, which is also used by vanilla spark scan. The second layer is the dataFilters of FileSourceScanExec, which is used to generate the pushedDownFilters of FileSourceScanExec, as well as the filters used after the current offload. The third layer is the condition of the filter. In theory, the filter condition contains dataFilters, and dataFilters contains pushedDownFilters.
The current implementation will push down dataFilters or condition filters. Simply rewrite dataFilters to pushedDownFilters may cause dataFilters to be pushed down before, but only pushedDownFilters can be pushed down.

**Comment by zhztheplayer** [comment]
@zml1206 Thanks for explanation. 

> Can we determine whether expression supports offload?
Let's see if https://github.com/apache/incubator-gluten/pull/6754 on which @rui-mo is working could finally help here.
