### ISSUE TITLE
[VL] Bump Spark to 3.5.3

### ISSUE THREAD

**Issue by Yohahaha** [apache/incubator-gluten#7336]
### Description

Spark has released v3.5.3, https://spark.apache.org/releases/spark-release-3-5-3.html

**Comment by PHILO-HE** [comment]
cc @zhouyuan, @weiting-chen, @FelixYBW

**Comment by FelixYBW** [comment]
Feel free to submit PR.

**Comment by zhouyuan** [comment]
I have made some draft on Spark 352 support(https://github.com/apache/incubator-gluten/pull/7138). The major changes are
- shuffle write API
- query plan tag removed
The missing part is on shim layers update. Looks like Spark 353 does not introduce big changes. I'll try to push out early next week


thanks, -yuan
