### ISSUE TITLE
[VL] RSS(Resident Set Size) memory of spark executor keep rising

### ISSUE THREAD

**Issue by wForget** [apache/incubator-gluten#7397]
### Backend

VL (Velox)

### Bug description

When I was analyzing spark executor being killed due to exceeding yarn memory limit, I found that rss memory of spark executor keeps rising even if spill occurs.

`OffHeapExecutionMemory` and `currently in use` have both decreased, but `ProcessTreeJVMRSSMemory` keeps rising.

![image](https://github.com/user-attachments/assets/d861525e-627e-44eb-8329-7ad01deed263)
![image](https://github.com/user-attachments/assets/1d2e7e78-c373-4545-a72d-a4094ac60098)
![image](https://github.com/user-attachments/assets/2fe46632-1727-4a5f-ae8a-5c02e91eada7)

### Spark version

Spark-3.5.x

**Comment by FelixYBW** [comment]
You may run the same query 50 times and check if RSS keep growing. If yes then it's a new mem leak.

**Comment by wForget** [comment]
> You may run the same query 50 times and check if RSS keep growing. If yes then it's a new mem leak.

Thanks, I will try this

**Comment by wForget** [comment]
After switching to jemalloc (support a new JemallocMemoryAllocator), it seems to be normal. And the sql that failed before can run successfully.

![image](https://github.com/user-attachments/assets/808c4dde-f34c-4b05-b6f7-68c8a6606744)
![image](https://github.com/user-attachments/assets/0d4fc199-b162-4751-95ca-52eb48c0c0d3)
![image](https://github.com/user-attachments/assets/169307e3-d3ab-4933-a6ce-8077428832ad)

**Comment by FelixYBW** [comment]
what allocator do you use previously?

**Comment by wForget** [comment]
> what allocator do you use previously?

I didn't configure it additionally before, is it the default `StdMemoryAllocator`?

https://github.com/apache/incubator-gluten/blob/4b6e929cccd31d0b6312dc4263746583321f022c/cpp/core/memory/MemoryAllocator.cc#L199

**Comment by FelixYBW** [comment]
Yes, by default it's libc. We always preload jemalloc, the test in last year shows jemalloc can boost perf by 10%.

You may also tune the jemalloc parameters and see if it can benefit your real workload. Main tuning is the decay value there, which controls how much memory jemalloc can hold before it returns the memory to system.

**Comment by wForget** [comment]
> We always preload jemalloc, the test in last year shows jemalloc can boost perf by 10%.

Thank you for your explanation. I am not familiar with C++ and jemalloc. I tried to implement a JemallocMemoryAllocator to introduce jemalloc. Is the `preload` method a more reasonable way? If so, could you share your configuration?

**Comment by FelixYBW** [comment]
> Thank you for your explanation. I am not familiar with C++ and jemalloc. I tried to implement a JemallocMemoryAllocator to introduce jemalloc. Is the `preload` way a more reasonable way? If so, could you share your configuration?

.set('spark.executorEnv.LD_PRELOAD',f'/usr/lib/{platform.machine()}-linux-gnu/libjemalloc.so.2')

**Comment by wForget** [comment]
> > Thank you for your explanation. I am not familiar with C++ and jemalloc. I tried to implement a JemallocMemoryAllocator to introduce jemalloc. Is the `preload` way a more reasonable way? If so, could you share your configuration?
> 
> .set('spark.executorEnv.LD_PRELOAD',f'/usr/lib/{platform.machine()}-linux-gnu/libjemalloc.so.2')

thank you

**Comment by wForget** [comment]
> .set('spark.executorEnv.LD_PRELOAD',f'/usr/lib/{platform.machine()}-linux-gnu/libjemalloc.so.2')

Thank you, I tried this way and it works fine.

**Comment by zml1206** [comment]
If `.set('spark.executorEnv.LD_PRELOAD',f'/usr/lib/{platform.machine()}-linux-gnu/libjemalloc.so.2')`, do we need to enable build_jemalloc when building? @FelixYBW @wForget

**Comment by wForget** [comment]
> Before `.set('spark.executorEnv.LD_PRELOAD',f'/usr/lib/{platform.machine()}-linux-gnu/libjemalloc.so.2')`, do we need to enable build_jemalloc when building? @FelixYBW @wForget

No need, the preload way does not rely on gluten binding jemalloc

**Comment by zml1206** [comment]
> No need, the preload way does not rely on gluten binding jemalloc

Thanks.

**Comment by wForget** [comment]
@zml1206 You can also refer to https://github.com/apache/incubator-gluten/blob/main/docs/developers/ProfileMemoryOfGlutenWithVelox.md#profiling-using-jemalloc, just remove the profile configurations.
