### ISSUE TITLE
Compilation failure of BufferAllocator

### ISSUE THREAD

**Issue by nakhanha** [apache/incubator-gluten#7423]
### Problem description

```
 
 val allocator =  ArrowBufferAllocators.contextInstance()
    val cSchema = ArrowSchema.allocateNew(allocator)
    val cArray = ArrowArray.allocateNew(allocator)

    val rb = ArrowAbiUtil.importToArrowRecordBatch(allocator,  cSchema, cArray)
 ```   
  ```  this snippet fails with error
    found   : BufferAllocator (in org.apache.gluten.shaded.org.apache.arrow.memory) 
 required: BufferAllocator (in org.apache.arrow.memory) 
 ```
 is there any utility that we can use ?

### System information

java 11

**Comment by nakhanha** [comment]
ArrowBufferAllocators brings shaded BufferAllocator where as ArrowAbiUtil expected non shaded one

**Comment by zhztheplayer** [comment]
This is unexpected with a regular build. Would you like to share more information? E.g., build command, executed command, etc.

**Comment by nakhanha** [comment]
this is not a regular build.

i have another project where we have maven dependency on gluten-data and gluten-core jars

**Comment by nakhanha** [comment]
https://chungmin.hashnode.dev/unraveling-a-scala-type-mismatch-mystery

**Comment by PHILO-HE** [comment]
> https://chungmin.hashnode.dev/unraveling-a-scala-type-mismatch-mystery

@nakhanha, thanks for sharing this blog with us. cc @zhztheplayer

**Comment by zhouyuan** [comment]
@nakhanha good write up! For others run into this issue, I copied the conclusion in your blog post here

```
Knowing the root cause, we can work around the issue by writing a wrapper in Java that calls ArrowAbiUtil.exportFromSparkColumnarBatch and using the wrapper in Scala instead of the original method.

A more fundamental fix should be placed on the Gluten side, to avoid shading in public API, although it's possible that ArrowAbiUtil is not meant to be public.
```
