### ISSUE TITLE
Build Gluten 1.2.0 with Dynamic Linking 

### ISSUE THREAD

**Issue by z-anderson** [apache/incubator-gluten#7439]
### Problem description

We know that it's recommended to build gluten with static linking, but we need to build it with dynamic linking (for our own infrastructure reasons). We know that the dynamic linking approach should still be supported, but we haven't been able to get it to build with the new  minor version 1.2.0 (we were able to build with 1.1.3). Can you give us some suggestions, please? 

We're getting this error 
`Caused by: java.lang.UnsatisfiedLinkError: /tmp/gluten-44bd150e-5d84-4c45-9cee-cc8150214577/jni/815a69da-5eff-48f7-b1bf-84c3059ea4ee/gluten-14667935902554126713/libgluten-x86_64.so: /tmp/gluten-44bd150e-5d84-4c45-9cee-cc8150214577/jni/815a69da-5eff-48f7-b1bf-84c3059ea4ee/gluten-14667935902554126713/libgluten-x86_64.so: undefined symbol: _ZTIN6apache6thrift8protocol9TProtocolE`

### System information

Velox System Info v0.0.2
Commit: ba042a8546be1743e54533d899cdc83dace24cfe
CMake Version: 3.16.3
System: Linux-5.15.0-1070-aws
Arch: x86_64
CPU Name: Model name:                           Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 9.4.0
C Compiler: /usr/bin/cc
C Compiler Version: 9.4.0
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt
  
\nThe results will be copied to your clipboard if xclip is installed.

### CMake log

```bash
Caused by: java.lang.UnsatisfiedLinkError: /tmp/gluten-44bd150e-5d84-4c45-9cee-cc8150214577/jni/815a69da-5eff-48f7-b1bf-84c3059ea4ee/gluten-14667935902554126713/libgluten-x86_64.so: /tmp/gluten-44bd150e-5d84-4c45-9cee-cc8150214577/jni/815a69da-5eff-48f7-b1bf-84c3059ea4ee/gluten-14667935902554126713/libgluten-x86_64.so: undefined symbol: _ZTIN6apache6thrift8protocol9TProtocolE
```

**Comment by PHILO-HE** [comment]
@z-anderson, by default, Gluten's script will install thrift to /usr/local. I guess your build env. has a conflict thrift version. Maybe, you can remove the existing thrift and build gluten again.

**Comment by PHILO-HE** [comment]
@z-anderson, BTW, could you let use know why dynamic linking must be required on your side? We may deprecate dynamic linking in the future if there is no strong reason to keep it according to users' feedback.

**Comment by ted-jenks** [comment]
Hey @PHILO-HE, resolved the thrift issue, thank you.

The build guide in the [docs](https://gluten.apache.org/docs/getting-started/velox-backend/#build-gluten-with-velox-backend) outlines the dynamic approach and outlines how we should end up with a [package jar with the libs](https://gluten.apache.org/docs/getting-started/velox-backend/#dependency-library-deployment). However, we have found that this does not work and the package jar is in fact empty. We currently have a set up like the old thirdparty jar which works. I was wondering, do the docs need updating to make it clearer that static builds are the way to go and the auto generation of the dependency jar is not supported?

We will try to migrate to static now. Makes sense for numerous reasons. The blockers we are hitting right now revolve around the CI information security requirements we have in place. Hopefully we can sort this out but will come back if we hit any blockers in the process.

Congrats and thanks for 1.2.0!

**Comment by PHILO-HE** [comment]
@ted-jenks, yes, the doc needs to be updated. I will do that today. Thanks for your feedback!

**Comment by PHILO-HE** [comment]
Assume this issue has been fixed. Closing it.
