### ISSUE TITLE
[CORE] Iceberg and hudi module  may breaks with Spark35

### ISSUE THREAD

**Issue by Yohahaha** [apache/incubator-gluten#7637]
### Backend

VL (Velox)

### Bug description

Gluten has upgrade Spark version to v3.5.3 https://github.com/apache/incubator-gluten/pull/7537, but iceberg may has compatibility issue with Spark 3.5.3.
https://github.com/apache/incubator-gluten/pull/7537#issuecomment-2428355077

### Spark version

None

**Comment by PHILO-HE** [comment]
Seems iceberg skips spark-3.5.3, see https://github.com/apache/iceberg/pull/11160. cc @zhouyuan

**Comment by zhztheplayer** [comment]
@Yohahaha Similar to https://github.com/apache/incubator-gluten/issues/7571, I think we should keep iceberg + Spark35 support in Gluten's next minor release (1.3.0). Any thoughts?

**Comment by Yohahaha** [comment]
> @Yohahaha Similar to #7571, I think we should keep iceberg + Spark35 support in Gluten's next minor release (1.3.0). Any thoughts?

iceberg decides skip spark 3.5.3, do we have better options?

**Comment by jackylee-ch** [comment]
https://github.com/apache/spark/pull/48257 is the related spark pr that fix the extension problem for iceberg, and it will be released in spark 3.5.4. And iceberg would skip 3.5.3 and keep up with 3.5.4 after spark 3.5.4 is released.
I'm afraid they won't be released before we release Gluten 1.3.0.

**Comment by baibaichen** [comment]
> @Yohahaha Similar to #7571, I think we should keep iceberg + Spark35 support in Gluten's next minor release (1.3.0). Any thoughts?
> 
> cc @baibaichen

@zhztheplayer @zhouyuan  @zzcclp

It depends on which is impormant, supporting hudi and icerberg in spark 3.5.3 or supporting spark 3.5.3.

I guess spark 3.5.3 is not used in most cases,  is there any reason that we must support spark 3.5.3? if not, I think revert to support 3.5.2 would be better

**Comment by zhztheplayer** [comment]
It seems https://github.com/apache/incubator-gluten/pull/7537 didn't involve any code changes, it's probably easy to maintain as an individual patch.

@Yohahaha Would you exclude the possibility maintaining #7537 internally in your Gluten fork? Until iceberg / hudi bump their Spark version?

**Comment by Yohahaha** [comment]
@baibaichen @zhztheplayer any reason we must checkout release 1.3.0 from current main branch? why not checkout from the commit before 7537?
or we can checkout release 1.3.0 and revert 7537.

The important things is Spark latest release version on branch 3.5 is v3.5.3, Gluten's strategy is keep latest Spark release version, do we want change it?

**Comment by baibaichen** [comment]
>  Gluten's strategy is keep latest Spark release version, do we want change it?

Gluten's strategy is supporting one version instead of latest release version due to lack of resource.  Perhaps starting from version 3.5,  we can support a stable version 3.5.2, and a latest version 3.5.3.  Of course, this needs further disscussion.

Back to https://github.com/apache/incubator-gluten/pull/7537,  we don't change any meaningful codes, we can still using it in spark 3.5.3 even it was reverted.

**Comment by FelixYBW** [comment]
@Yohahaha Gluten tends to support latest spark release but since iceberg doesn't support spark3.5.3. Iceberg support is more important in Gluten now. Can we skip 3.5.3? once 3.5.4 fix the iceberg issue, we can add spark3.5.4.

**Comment by PHILO-HE** [comment]
We were not aware of such issue before. Maybe, it's time to change our previous convention for upgrading Spark minor release. I have created one discussion: https://github.com/apache/incubator-gluten/discussions/7874.

**Comment by Yohahaha** [comment]
I will revert spark version to 3.5.2 if no one takes it.

**Comment by Yohahaha** [comment]
but I'm confused why GHA still passed with iceberg tests, I only remove hudi profile when upgrading spark 353.

**Comment by gaoyangxiaozhu** [comment]
> but I'm confused why GHA still passed with iceberg tests, I only remove hudi profile when upgrading spark 353.

+1 why CI passed

**Comment by Yohahaha** [comment]
![image](https://github.com/user-attachments/assets/24b0655f-6579-4f2c-9e32-f23cf0b9d59e)

that's interesting, iceberg tests pass actually...

anyway, let's continue revert to spark 352, if no questions.

**Comment by FelixYBW** [comment]
> 
> that's interesting, iceberg tests passed actually...
> 
> anyway, let's continue revert to spark 352, if no questions.

@PHILO-HE any insight?

**Comment by PHILO-HE** [comment]
> > that's interesting, iceberg tests passed actually...
> > anyway, let's continue revert to spark 352, if no questions.
> 
> @PHILO-HE any insight?

@FelixYBW, the existing iceberg tests in Gluten may not have enough coverage.
