### ISSUE TITLE
[VL] VeloxBackend should know it run in executor or driver

### ISSUE THREAD

**Issue by leoluan2009** [apache/incubator-gluten#7837]
### Description

VeloxBackend show know where it run, executor or driver? for example if if run driver ,it should not init velox cache. There are two methods to this enhancement:
1. pass a config spark.gluten.isDriver when creating VeloxBackend instance, this is simple.
2. Add a member variables in VeloxBackend class, need to change jni code.

**Comment by leoluan2009** [comment]
@zhztheplayer   @zhouyuan  can you give some thoughts? thanks!

**Comment by zhztheplayer** [comment]
Driver and executor do have different plugin entrypoints, https://github.com/apache/incubator-gluten/blob/main/backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala, are you suggesting a new approach?

**Comment by leoluan2009** [comment]
> Driver and executor do have different plugin entrypoints, https://github.com/apache/incubator-gluten/blob/main/backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala, are you suggesting a new approach?

But in VeloxBackend.cc, we can not know where it run

**Comment by zhztheplayer** [comment]
> > Driver and executor do have different plugin entrypoints, https://github.com/apache/incubator-gluten/blob/main/backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala, are you suggesting a new approach?
> 
> But in VeloxBackend.cc, we can not know where it run. The info do not pass from java code to cpp code

I see. Do you know which part of C++ code requires for this information?

**Comment by leoluan2009** [comment]
> > > Driver and executor do have different plugin entrypoints, https://github.com/apache/incubator-gluten/blob/main/backends-velox/src/main/scala/org/apache/gluten/backendsapi/velox/VeloxListenerApi.scala, are you suggesting a new approach?
> > 
> > 
> > But in VeloxBackend.cc, we can not know where it run. The info do not pass from java code to cpp code
> 
> I see. Do you know which part of C++ code requires for this information?

if it run in driver, it should not init velox cache. https://github.com/apache/incubator-gluten/blob/main/cpp/velox/compute/VeloxBackend.cc#L197

**Comment by zhztheplayer** [comment]
I am curious why it matters to initialize the cache in driver or not. Do you already see some issues or errors in your circumstance? 

BTW I'll prefer changing the JNI API to have different patches for driver / executor native initializations if we have to do it.

**Comment by leoluan2009** [comment]
> I am curious why it matters to initialize the cache in driver or not. Do you already see some issues or errors in your circumstance?
> 
> BTW I'll prefer changing the JNI API to have different patches for driver / executor native initializations if we have to do it.

Yes, when initialize the cache, it will create cache dir and check remaining disk capacity while spark driver node may has smaller disk than executor.

**Comment by FelixYBW** [comment]
Do we start any Velox pipeline on driver today? Where the cache is initialized?

Looks only the BHJ's hash build may be run on driver which we haven't implemented yet.

**Comment by LoseYSelf** [comment]
> Do we start any Velox pipeline on driver today? Where the cache is initialized?
> 
> Looks only the BHJ's hash build may be run on driver which we haven't implemented yet.
this line will check the ssd cahce space. https://github.com/apache/incubator-gluten/blob/c653337cdf54067cd4a01d14b908a521fdd11b3a/cpp/velox/compute/VeloxBackend.cc#L217

**Comment by LoseYSelf** [comment]
> Do we start any Velox pipeline on driver today? Where the cache is initialized?
> 
> Looks only the BHJ's hash build may be run on driver which we haven't implemented yet.

this line will check ssd space.
https://github.com/apache/incubator-gluten/blob/c653337cdf54067cd4a01d14b908a521fdd11b3a/cpp/velox/compute/VeloxBackend.cc#L217

**Comment by FelixYBW** [comment]
Thank you. Then we should initialize velox on driver and worker differently.
