### ISSUE TITLE
 [CORE]  Distinguish between native scan and vanilla spark scan in plan tree string

### ISSUE THREAD

**Issue by zml1206** [apache/incubator-gluten#7847]
### Description

Currently, the nodeName of navtive scan are the same as vanilla spark scan, making it impossible to distinguish them in planTreeString.

For example, for `FileSourceScanExec`:
update nodeName from "Scan **" to "NativeScan **"
update nodeNamePrefix from "NativeFile" to "File"

**Comment by zml1206** [comment]
@zhztheplayer Do you think it is necessary to modify？

**Comment by FelixYBW** [comment]
Not a big issue. We may align with other operator name like ScanTransformer
