### ISSUE TITLE
[UI] Optimize cleanup gluten sql executions ui data

### ISSUE THREAD

**Issue by zml1206** [apache/incubator-gluten#7890]
### Description

There is a phenomenon in our production environment. After running for a period of time, only a few gluten sql executions ui data will be retained. We are resident in spark, and there are some queries that disable gluten.
The reason is that the current cleanup of gluten sql executions ui data depends on SQLExecutionUIData. There is a problem here. When sql execution disables gluten, gluten sql executions ui data will not be generated, but cleanup will still be triggered.

**Comment by gaoyangxiaozhu** [comment]
curious if we disable gluten， why the event of `GlutenSQLAppStatusListener` still be triggerred ?

**Comment by zml1206** [comment]
> curious if we disable gluten， why the event of `GlutenSQLAppStatusListener` still be triggerred instead of been disabled also?


`GlutenSQLAppStatusListener` is registered by `GlutenPlugin`, this is done by driver initialization.

**Comment by gaoyangxiaozhu** [comment]
> > curious if we disable gluten， why the event of `GlutenSQLAppStatusListener` still be triggerred instead of been disabled also?
> 
> `GlutenSQLAppStatusListener` is registered by `GlutenPlugin`, this is done by driver initialization.

thanks @zml1206 , so i am just wondering does it possbile to let glutenPlugin do nothing (at least not register gluten listener) if gluten is been disabled by `spark.gluten.enabled` conf ?

**Comment by zml1206** [comment]
> so i am just wondering does it possbile to let glutenPlugin do nothing (at least not register gluten listener) if gluten is been disabled by `spark.gluten.enabled` conf ?

AFAIK, this is inappropriate because `spark.gluten.enabled` is a dynamic configuration, while listener is static and cannot be changed after initialization.
