### ISSUE TITLE
[VL] Track the changes on building flags

### ISSUE THREAD

**Issue by zhouyuan** [apache/incubator-gluten#8041]
### Description

The default building flags of Gluten is set with "march=native" which will optimize most of local CPU architecture, but this will introduce some compatibility issues when running on other CPU architectures. So ideally Gluten should build low optimization level and allow distributed wild.

**Comment by majetideepak** [comment]
@zhouyuan Is this complete?

**Comment by zhouyuan** [comment]
@majetideepak Yes, it's done on aligning with Velox building profile so the compatibility issues when running on other CPU platform(diff with packaging platform) should be fixed. I will try to add one more profile ("march=native")

**Comment by FelixYBW** [comment]
@zhouyuan does the profile impact vcpkg flags as well? vcpkg should be aligned with Velox always.

Let's also support marchs of GCC flags. In long term velox should support avx512.

**Comment by zhouyuan** [comment]
> @zhouyuan does the profile impact vcpkg flags as well? vcpkg should be aligned with Velox always.
> 
> Let's also support marchs of GCC flags. In long term velox should support avx512.

@FelixYBW right, currently vcpkg libs are using a customized `avx2` triplet:
https://github.com/apache/incubator-gluten/blob/main/dev/vcpkg/triplets/x64-linux-avx.cmake
