### ISSUE TITLE
[CI] Github action tests on Centos7 is broken

### ISSUE THREAD

**Issue by zhouyuan** [apache/incubator-gluten#8046]
### Backend

VL (Velox)

### Bug description

/__e/node20/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /__e/node20/bin/node)/__e/node20/bin/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /__e/node20/bin/node)/__e/node20/bin/node: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /__e/node20/bin/node)/__e/node20/bin/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /__e/node20/bin/node)/__e/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)/__e/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /__e/node20/bin/node)

### Spark version

None

**Comment by zhouyuan** [comment]
https://github.com/actions/runner-images/issues/10896

**Comment by zhouyuan** [comment]
https://github.com/apache/incubator-gluten/pull/8042

**Comment by kanwalmeetsingh** [comment]
Hi 
We are facing same issue on public.ecr.aws/sam/build-python3.8:latest-x86_64 image
/__e/node20/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /__e/node20/bin/node)


It was working until yesterday now stopped. 
Any help is appreciated

Thanks
![image](https://github.com/user-attachments/assets/7701117e-f249-499f-8ed5-fe86faaa83e0)
