### ISSUE TITLE
build_protobuf=ON: command not found

### ISSUE THREAD

**Issue by avs-alatau** [apache/incubator-gluten#8134]
### Problem description

`./dev/buildbundle-veloxbe.sh --enable_vcpkg=ON --enable_hdfs=ON --build_protobuf=ON --spark_version=3.5`

_./dev/builddeps-veloxbe.sh: line 281: --build_protobuf=ON: command not found_

without --build_protobuf=ON it is going to be successful

### System information

Gluten Version: 1.3.0-SNAPSHOT
Commit: cd51ecac39ce080597ce95d82d0c3ceeb8f2524e
CMake Version: 3.16.3
System: Linux-5.4.0-196-generic
Arch: x86_64
CPU Name: Model name:                         Intel(R) Xeon(R) Silver 4314 CPU @ 2.40GHz
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 9.4.0
C Compiler: /usr/bin/cc
C Compiler Version: 10.5.0
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

### CMake log

```bash
......
+ echo 'Applying patch to Velox source code...'
Applying patch to Velox source code...
+ git apply modify_velox.patch
+ '[' 0 -ne 0 ']'
+ echo 'Finished getting Velox code'
Finished getting Velox code
++ '[' '' == '' ']'
++ VELOX_HOME=/opt/test/gluten/dev/../ep/build-velox/build/velox_ep
+++ uname -s
++ OS=Linux
+++ uname -m
++ ARCH=x86_64
++ DEPENDENCY_DIR=/opt/test/gluten/dev/../ep/_ep
++ mkdir -p /opt/test/gluten/dev/../ep/_ep
++ source /opt/test/gluten/dev/../dev/build_helper_functions.sh
++ '[' -z /opt/test/gluten/dev/vcpkg/.vcpkg ']'
++ commands_to_run=--build_protobuf=ON
++ [[ x--build_protobuf=ON == \x ]]
++ echo 'Commands to run: --build_protobuf=ON'
Commands to run: --build_protobuf=ON
++ for cmd in "$commands_to_run"
++ --build_protobuf=ON
./dev/builddeps-veloxbe.sh: line 281: --build_protobuf=ON: command not found
```

**Comment by wForget** [comment]
`build_protobuf` has been removed since #7518
