### ISSUE TITLE
[CH] Adjusting the build side is not enough

### ISSUE THREAD

**Issue by lgbo-ustc** [apache/incubator-gluten#8167]
### Backend

CH (ClickHouse)

### Bug description

[Expected behavior] and [actual behavior].

At present , we could pick up a proper build side, but we still need to swith the tables.

We met a case
```
                                    CHShuffledHashJoinExecTransformer LeftOuter BuildLeft (128)
      :                    :        :              :- ^ InputIteratorTransformer (99)
      :                    :        :              :  +- ShuffleQueryStage (97), Statistics(sizeInBytes=560.2 MiB, rowCount=8.71E+6)
                                                   +- ^ InputIteratorTransformer (127)
      :                    :        :                 +- ShuffleQueryStage (125), Statistics(sizeInBytes=177.3 GiB, rowCount=5.46E+9)
      :                    :        :                    +- ColumnarExchange (124)
```
The build side is correct, left table is smaller. But in fact, CH runs a right join, and still uses the right table as build table.

### Spark version

None

**Comment by zhanglistar** [comment]
Reorder bug?

**Comment by lgbo-ustc** [comment]
Not really a bug. vanilla has told to build the left table, but we don't in fact
